### ISSUE TITLE
Logos does not support tokens with type parameters

### ISSUE THREAD

**Issue by Marwes** [maciejhirsz/logos#123]
Thought I would give logos a try but I unfortunately just refactored my `Token` type to have a type parameter which logos does not support.
https://github.com/gluon-lang/gluon/pull/831/files#diff-9c5ddb4ecdc6545528e1bbb12264ac64R19

The idea of the type parameter here is that the lexer itself will only work with a `type BorrowedToken<'input> = Token<&'input str>` but when using the `Token` in errors they can instead use  `Token<String>` to avoid being bound to the input.¨

Any chance this case can be supported? Without knowing much about the internals, a quick hack may be to add an attribute which allows an alias (`BorrowedToken<'input>`) be used as the actual `Token` type as far as the procedural macro is concerned

**Comment by maciejhirsz** [comment]
It won't work with a generic `S`, but it should work fine if the implementation uses a concrete type, which could be done with an attribute. Something like this perhaps:

```rust
#[derive(Logos)]
#[logos(for S = &str)]
pub enum Token<S> {
// ...
```

**Comment by Marwes** [comment]
That should work for my use case at least!

**Comment by maciejhirsz** [comment]
This is now on `master`, see #128 for details. I plan to roll out 0.11.1 sometime during the weekend so I can handle other issues flagged for that release.

**Comment by maciejhirsz** [comment]
@Marwes this is [now published](https://github.com/maciejhirsz/logos/releases/tag/v0.11.1).
