### ISSUE TITLE
Document how to create // style comments in Logos

### ISSUE THREAD

**Issue by rickprice** [maciejhirsz/logos#124]
Hi,

I have looked at the tests and the ReadMe, and I can't quite figure out how to create a Regex to collect the contents of a c# // style comment. (goes to end of line, or end of input).

Could you please explain how to do that, particularly in a test or the ReadMe?

**Comment by Kixiron** [comment]
If you don't want to capture the newline, then `//[^\r\n]*` and `//[^\n]*` work, if you want to capture the newline then use `//.*\n` and `//.*\n`

**Comment by maciejhirsz** [comment]
We should probably have an `examples` folder with sample lexers for JS and CSS.

**Comment by rickprice** [comment]
Thanks for the example, but what about when the comment ends at the end of the string, but without a newline? How do I handle that? IE does Logos handle the $ character, and does it work like a multiline Regex?

Like:

"This is // a test\n"
"This is // a test\r\n"
"This is // a test"

I would like to be able to match all three with the simplest Regex possible.

Thanks for the help.

**Comment by maciejhirsz** [comment]
`r"//[^\r\n]*(\r\n|\n)?"` should work

**Comment by rickprice** [comment]
Okay, I got that working, but how do I do C style comments now: /* .... */ ?

I've tried the below, but it's not seeming to work for me, I keep getting the Error token:

#[regex(r#"/\*.*\\*/"#)]
CComment,

**Comment by maciejhirsz** [comment]
`r"\/\*([^*]|\*[^\/])+\*\/"`

I recommend playing on [regex101.com](https://regex101.com/) to see if things work:

![Screenshot from 2020-04-21 08-53-27](https://user-images.githubusercontent.com/1096222/79834588-9de78c80-83ad-11ea-903c-bb278410ce06.png)

**Comment by AshtonSnapp** [comment]
I imagine an assembler style comment (i.e. ; blah blah blah) would be similar to a c-style // in terms of regex?

**Comment by thetayloredman** [comment]
what about nested c-like block comments?

**Comment by jeertmans** [comment]
@thetayloredman you should match the start and end of block comments with two separate tokens. Then the role of some parser function would be to skip treat all the tokens in between as comments, and handle possible nested blocks.
