### ISSUE TITLE
Feature request: {n,m} repetitions

### ISSUE THREAD

**Issue by CAD97** [maciejhirsz/logos#126]
This shouldn't be too difficult to add support for.

As an example, `\\u\{(?:10|[0-9])[0-9a-fA-F]{0,4}\}` would just expand to `\\u\{(?:10|[0-9])[0-9a-fA-F]?[0-9a-fA-F]?[0-9a-fA-F]?[0-9a-fA-F]?`.

That is, expand to `n` copies of the repeated node and `m-n` copies of the repeated node but optional.

The "regex optimized" version would be expanding to nested optionals, so `nnn(?:m(?:m(?:m)?)?)?`.

**Comment by CAD97** [comment]
Context: I'm working on formalizing the Rust lexical grammar. It uses `{n,m}` repetition to keep the regex rules somewhat readable.

**Comment by maciejhirsz** [comment]
Ye, if we keep them constrained (say `m < 5`?) that should be fine. This can be easily done in my [intermediate regex representation](https://github.com/maciejhirsz/logos/blob/96faa6bb9954fd9e370f04ee703b5e67494cecf1/logos-derive/src/graph/regex.rs#L12-L25) now :).

**Comment by Evrey** [comment]
`m < 5` is quite short. Imagine using that for 128-bit int literals. You can limit it to 2¹⁶-1 as an impl detail, but at least with binary integer literals you'll hit big numbers quickly. You can `warn` users of Logos with a lint, though, if numbers exceed, say, 16, so that *if* Logos OOM crashes unrolling the regex or takes a billion years to compile, the user knows why.

**Comment by maciejhirsz** [comment]
It might be reasonable to have some heuristic that checks complexity of the thing you are trying to expand. For example `fo{20}` is almost definitely fine since it just expands to `foooooooo...`, but `\w{20}` would be like over 4000 nodes on the state machine graph.

**Comment by Evrey** [comment]
Sadly I don't know how to lint in Rust. =D Have never written a procmacro before. But yeah, that heuristic makes absolute sense.

**Comment by maciejhirsz** [comment]
The way errors from proc macros work, is that you spit out a [`compile_error!`](https://doc.rust-lang.org/std/macro.compile_error.html) spanned to where in the source code you want to highlight something, your macro can then expand into something that includes many instances of `compile_error!(...)`, at which point `rustc` intervenes and dumps them out. Sadly we don't have a `compile_warn!` :).

**Comment by CAD97** [comment]
There's definite desire to add a way for proc macros to be able to emit warnings -- the first-class way being [`#![feature(proc_macro_diagnostic)]`](https://github.com/rust-lang/rust/issues/54140). [`proc-macro-error`](https://crates.io/crates/proc-macro-error) seems to offer shimming both the error and warning APIs for stable usage (but with warnings only doing something on the nightly channel).

The main sticking point for a warning API is that there needs to be some way to attach a lint name to them, so that they can be manipulated by `#[allow]`, `#[warn]`, `#[deny]`, and such.

**Comment by CAD97** [comment]
Example problematic regex: `[01]*1[01]{N}` creates a DFA with `2^(N+1)` states [according to regex-automata](https://docs.rs/regex-automata/0.1.9/regex_automata/#differences-with-the-regex-crate).

As an alternative: pick some arbitrary limit for the number of nodes and enforce that limit when compiling. This wouldn't be able to point at _why_ a regex is too complex, but it would guaranteed catch _all_ such cases.

Logos doesn't have to worry _too_ much about ReDoS-style exponential blowup, because all given regexes are "trusted" and given by the developer rather than a potentially malicious source. A cap to the size of the calculated DFA would then just be primarily a lint to prevent compilation from taking forever, and you could also offer a knob to increase that limit.

**Comment by maciejhirsz** [comment]
@CAD97 my state machine graph implementation doesn't have any explosive behavior here.

`[01]*1[01][01][01][01][01][01][01][01][01][01][01][01][01][01][01][01][01][01]` produces graph:

```
{
    1: "MATCH",
    2: 1[0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1][0-1] ⇒ 1,
    3: {
        [0-1] ⇒ 3,
        _ ⇒ 2,
    },
}
```

Node 2 is a "rope" which is just the pattern repeated n times, so there are no issues here.

**Comment by CAD97** [comment]
Either your graph is nondeterministic, blows up exponentially on that regex, or doesn't implement that regex correctly.

Assuming that control flow graph is complete and starts at state 3, it looks like it gets the regex wrong or is nondeterministic. How does it know when to exit state 3 given a string of just `0`s and `1`s?

Note that a purely NFA engine is not vulnerable to ReDoS at all. (At least according to the Wikipedia page) It's only backtracking and complete/eager DFA construction that can be attacked, and NFA simulation (where you hold the state as a set of states) and (well tuned) lazy DFA construction aren't suseptible to ReDoS.

**Comment by maciejhirsz** [comment]
> Either your graph is nondeterministic, blows up exponentially on that regex, or doesn't implement that regex correctly.

Looking at it again now that I woke up and had some coffee, it's definitely the last option. Logos does only very limited backtracking, and it never does it across loop boundaries, so it will fail in this case. I'm actually perfectly fine with that state of affairs since Logos only meant to handle a subset of regex, though it would be nice to detect a broken regex like this and throw an error on compile time, just as it does for non-greedy flag `?`. I'm going to open an issue for this.

As to the feature in question here, given there is no exploding behavior in Logos here, a simple heuristic on `{n,m}` should be entirely sufficient.

**Comment by nalply** [comment]
I tried a `{n,m}` repetition with Unicode properties and it blew up horribly.

```rust
// cargo-deps: logos="0.13"

use logos::{Lexer, Logos};

#[derive(Logos, Debug, PartialEq)]
pub enum Words {
  #[regex("[ \n\r\t]+")]
  WhiteSpace,

  #[regex("[\\pL]{1,10}", to_string)]
  Word(String),

  #[regex(".+", to_string, priority = 0)]
  Any(String),
}

fn to_string(lex: &mut Lexer<Words>) -> String { lex.slice().to_string() }

fn main() {
  let mut lex = Words::lexer("test");
  println!("{:?}", lex.next());
}
```

This took a long time to analyze and compile and greate a large graph.

```
> cargo run --example grammar1
   Compiling sand_lex v0.1.0 (/home/nalp/Projects/sand/sand_lex)
     Finished dev [unoptimized + debuginfo] target(s) in 5.24s
     Running `target/debug/examples/grammar1`
Some(Ok(Word("test")))
> cargo expand --example grammar1 | wc -l
    Checking sand_lex v0.1.0 (/home/nalp/Projects/sand/sand_lex)
    Finished dev [unoptimized + debuginfo] target(s) in 1.42s

375448
> cargo bloat --example grammar1 --filter 'grammar1|logos' -n 0 | tail -n -1
    Finished dev [unoptimized + debuginfo] target(s) in 5.41s
    Analyzing target/debug/examples/grammar1

16.0% 83.9% 1.7MiB           filtered data size, the file size is 10.5MiB
```

Replacing `{1,10}` with `+` yields:

```
> cargo run --example grammar1
    Finished dev [unoptimized + debuginfo] target(s) in 0.88s
     Running `target/debug/examples/grammar1`
Some(Ok(Word("test")))
> cargo expand --example grammar1 | wc -l
    Checking sand_lex v0.1.0 (/home/nalp/Projects/sand/sand_lex)
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s

36527
> cargo bloat --example grammar1 --filter 'grammar1|logos' -n 0 | tail -n -1
   Compiling sand_lex v0.1.0 (/home/nalp/Projects/sand/sand_lex)
    Finished dev [unoptimized + debuginfo] target(s) in 0.75s
    Analyzing target/debug/examples/grammar1

3.2% 38.1% 165.9KiB           filtered data size, the file size is 5.0MiB
```

This means about a tenth of size about about a fifth of compiling time. Compiling times can become very bad. A repetition `{1,100}` could take almost a minute to compile.

A workaround would be giving the lexer only short slices as input and write the grammar in a way that it still does its job if the input is chopped up. Do you have a better ideas for a workaround?

**Comment by jeertmans** [comment]
Hello @CAD97, thank you for this analysis!

I think `{n,m}` repetition is actually supported, and this issue should be closed.

What you are mentioning is more performance issue, and I think it would be worth to open a new issue on that regard. What do you think?

**Comment by jeertmans** [comment]
Closing this a too old, feel free to re-open if needed.
