### ISSUE TITLE
Feature request: manually specify disambiguation priority

### ISSUE THREAD

**Issue by CAD97** [maciejhirsz/logos#127]
I'm providing an implementation of my proposed Rust lexical grammar based on logos. The disambiguation logic of logos almost does the right thing, but I need to override the behavior to break ties that exist in the lexical grammar as specified.

Specifically, the failing test that I'm seeing is for

```rust
#[allow(nonstandard_style)]
#[derive(Logos)]
enum TokenKind {
    /* ,.. */
    #[regex(r"\p{XID_Continue}+")]
    identifier_fragment,
    /* ... */
    #[regex(r"[0-9][_0-9]*")]
    decimal_integer,
    /* ... */
}
```

where `decimal_integer` is defined to be preferred when tying with `identifier_fragment`.

The implemented behavior _seems_ to be to prefer earlier-defined rules in the case of a priority tie. In this case, I think I would get the correct result by just giving `identifier_fragment` a priority adjustment of `-1` (for a final priority of `0`).

I could probably reorder rules to get the correct behavior, but this moves the logos implementation further away from the naive reference spec implementation, so would be undesirable.

**Comment by CAD97** [comment]
The underlying issue has been fixed by changing the `identifier_fragment` to the more correct regex `[\p{XID_Continue}--_0-9\p{XID_Continue}]\p{XID_Continue}*` throughout the spec. (I was unaware that `\p` classes worked in `[]` classes.)

It'd still be nice to be able to manually specify priority (adjustments?) for tokens, though, to handle when the automatic priority doesn't quite do the job.

**Comment by maciejhirsz** [comment]
Ye, this is somewhat related to #22. Currently if the priorities are equal it will still pick one other the other token (based on order in which they are defined), which irks me a bit.

What it should do is (as suggested in #22) give you an errors, show you which two definitions are in conflict, and then suggest adding manual priority overrides. Those would be something like `#[regex("...", priority = 10)]`.

**Comment by maciejhirsz** [comment]
New errors incoming:

```
   Compiling tests v0.0.0 (/home/maciej/rust/logos/tests)
error: A definition of variant `Abc` can match the same input as another definition of variant `Cde`.

hint: Consider giving one definition a higher priority: #[regex(..., priority = 2)]
   --> tests/tests/edgecase.rs:413:17
    |
413 |         #[regex("[cde]+")]
    |                 ^^^^^^^^

error: A definition of variant `Cde` can match the same input as another definition of variant `Abc`.

hint: Consider giving one definition a higher priority: #[regex(..., priority = 2)]
   --> tests/tests/edgecase.rs:410:17
    |
410 |         #[regex("[abc]+")]
    |                 ^^^^^^^^

error: aborting due to 2 previous errors
```

:)

**Comment by maciejhirsz** [comment]
Released, [notes](https://github.com/maciejhirsz/logos/releases/tag/v0.11.1)
