### ISSUE TITLE
how to parse utf8 token?

### ISSUE THREAD

**Issue by bitbegin** [maciejhirsz/logos#136]
it will be good to provide a way to modify the input string position. when it encounter a utf8 byte, check the utf8 length, then move the input string position by the length.

**Comment by maciejhirsz** [comment]
Logos already supports unicode by breaking out unicode ranges into byte ranges internally. if you need the length of the parsed token use `lexer.span().end - lexer.span().start`.

**Comment by bitbegin** [comment]
seems already supported
