### ISSUE TITLE
Issue with lexing multiline string

### ISSUE THREAD

**Issue by Alxandr** [maciejhirsz/logos#137]
I would expect the following to pass, but it doesn't:

```rust
#[test]
fn test() {
  use logos::Logos;

  #[derive(Logos, Debug, PartialEq)]
  enum Simple<'a> {
    #[regex("\"(?:[^\"\\\\]|\\\\.)*\"")]
    Str(&'a str),

    #[error]
    Err,
  }

  let mut lex = Simple::lexer("\"hi\\\n\"");
  assert_eq!(lex.next(), Some(Simple::Str("\"hi\\\n\"")));
}
```

It does pass on regex101: https://regex101.com/r/QoNSFW/1/

**Comment by maciejhirsz** [comment]
It won't pass if you disable the `s` flag :)

Try `#[regex(r#""([^"]|\\[^"])*""#)]`

**Comment by Alxandr** [comment]
Yeah, I've used raw strings for most of the regexes, except those requiring quotes. Mainly due to the fact that the tokenization in my editor doesn't handle them well.

**Comment by Alxandr** [comment]
This breaks escaping quotes :D. https://regex101.com/r/QoNSFW/2/. Guess I'll have to keep experimenting.

**Comment by Alxandr** [comment]
`"(?:[^"\\]|\\(?:.|\r\n|\n))*"` seems to do the trick, unless you have a better solution?

**Comment by Alxandr** [comment]
Better question though, how do I match any one "character"?

**Comment by maciejhirsz** [comment]
If `*` doesn't work, then `(*|\n)` should.

**Comment by Alxandr** [comment]
I assume you mean `.|\n`?

**Comment by maciejhirsz** [comment]
Yes :man_facepalming:

**Comment by Alxandr** [comment]
Thanks. I solved it using `.|\n`. That being said, should maybe the `s` flag be enabled (either by default, or optionally somehow)? I found it quite confusing that `\n` is handled specially.

**Comment by maciejhirsz** [comment]
You can enable flags in groups: https://regex101.com/r/Ksasmr/1

**Comment by Alxandr** [comment]
Brilliant: `#[regex("\"(?s:[^\"\\\\]|\\\\.)*\"")]`, thanks.

You might want to keep this for your "examples" book :P
