### ISSUE TITLE
consider function based tokens

### ISSUE THREAD

**Issue by sergeyt** [maciejhirsz/logos#146]
custom token can be faster than regex

```rust
fn str(lex: &mut Lexer<Token> -> {
  // ...
}

enum Token {
  #[func(str)]
  Str
}
```

maybe logos already supports it

**Comment by maciejhirsz** [comment]
You can use a callback, though you need at least one byte match:

```rust
fn str(lex: &mut Lexer<Token>) {
    // do something with lex.remainder()
    lex.bump(matched_bytes);
}

enum Token {
    #[token("\"", str)]
    Str
}
```

> custom token can be faster than regex

I'm willing to bet money that unless your callback is using hand-tailored SIMD instructions, code Logos generates from regex will be faster.

**Comment by sergeyt** [comment]
@maciejhirsz  just curious do you have custom regex impl that compiles in efficient code?

**Comment by maciejhirsz** [comment]
@sergeyt yes, Logos has it's own regex subset implementation that gets reduced to efficient Rust at compile time.
