### ISSUE TITLE
How to make token match until start of another token?

### ISSUE THREAD

**Issue by SoptikHa2** [maciejhirsz/logos#156]
Hi, let's suppose I have string like this:

```
START
  line
a
  second line
SECONDSEGMENT:
  abc
  def
  g
h
```

I would like to produce two matches. First one:
```
START
  line
a
  second line
```
Second one:
```
SECONDSEGMENT:
  abc
  def
  g
h
```

How can I match everything up to start of another segment, is there a way to do so? Something like this obviously doesn't work:
```rs
#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[regex("START(.|\n)*")]
    StartSegment,
    #[regex("SECONDSEGMENT:(.|\n)*")]
    SecondSegment,
    #[error]
    Error,
}
```

Is there a way to do this without making a regex that doesn't match on start of the another segment? In real application I'm building, I will have more segments like this and I don't want to build regex that matches anything-up-to-any-next-segment.

I had idea about matching just the segment header with one token, and then have universal token for "segment body". This has problems when the body is not simply anything inbetween two tokens but differs on token-to-token basis, but I suppose I could work around this. But I wasn't able to create tokens that would match it properly, even if I set priorities manually - the whole string is always matched by `AnySegmentBody`.

```rs
#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[token("START", priority = 100)]
    StartSegment,
    #[token("SECONDSEGMENT:", priority = 100)]
    SecondSegment,
    #[regex("(\n|.)+", priority = 1)]
    AnySegmentBody,
    #[error]
    Error,
}
```

What are the best practices regarding this, what is the right way to deal with this?

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=19d4d692a3136bd478920062356c677d) (doesn't compile as playground doesn't have Logos).

**Comment by maciejhirsz** [comment]
I think you are trying to have the lexer do a parsing job, which will give you a hard time. What you ought to try rather is to have a token for `START`, token for `SECONDSEGMENT:`, and tokens for other stuff in between.

Alternatively you can use lexer morphing with two separate enums, where one handles the `SECONDSEGMENT:` as a "closing" token. I've somewhat of [a working example of this in Ramhorns](https://github.com/maciejhirsz/ramhorns/blob/master/ramhorns/src/template/parse.rs).

**Comment by SoptikHa2** [comment]
Thank you! I'll look into it.
