### ISSUE TITLE
Matching with `*`

### ISSUE THREAD

**Issue by suhr** [maciejhirsz/logos#161]
I have the following definition:

```rust
#[derive(Logos, Debug, Clone, Copy, PartialEq)]
enum CommentToken {
    #[token("/*")]
    Start,
    #[token("*/", priority = 42)]
    End,

    #[regex(r".", logos::skip)]
    #[error]
    Error,
}
```

It seems to work fine. But when I change `.` to `.*`, the `End` token can no longer be matched.

Is this an expected behavior? And if so, how exactly token disambiguation works with `*` rules?

**Comment by suhr** [comment]
I can reproduce this with `..` instead of `.*`. So this is indeed a bug.

**Comment by maciejhirsz** [comment]
Yup, this is expected behavior, it's going to be in the book, along with examples for how to match block comments :).
