### ISSUE TITLE
Logos lexes comment start as an operator

### ISSUE THREAD

**Issue by suhr** [maciejhirsz/logos#166]
I have a bunch of rules in my lexer, including this two:

```rust
pub enum Token {
    #[regex(r"/\*", priority = 616)]
    CommentStart,
    #[regex(r"[~!@#\^\&|`?+\-*/%<>=]+")]
    Op,
}
```

Then I pass `/**/` to the lexer as an input.

**Expected behavior:** Logos should lex `/*` as a comment start
**Actual behavior:** Logos scans `/**/` as an operator.

PS: This is a complete list of tokens: https://gist.github.com/suhr/d0d27a76a759821718c278a048ea1cc6

**Comment by maciejhirsz** [comment]
This is expected behavior because the pattern for `Op` can match the whole `/**/`, which is the longest possible match.

**Comment by suhr** [comment]
Yeah, I figured this out. Still super annoying though.

By the way, I'm implementing my own lexer generator based on regular expressions derivatives. It supports regular expression intersection and complement, so I can express my intent more directly.

I'd like to have some ideas about code generation from DFA. It seems that Logos relies a lot on tail calls, but the problem is Rust doesn't really guarantee tail call elimination. I believe this problem can be workarounded by using labeled break/continue for strongly connected components of DFA, but I didn't quite figure out yet how to do it.

Directed graphs with cycles are tricky.

**Comment by windelbouwman** [comment]
Interesting you mention regular expression derivatives, checkout this library implementing this idea in python: https://github.com/MichaelPaddon/epsilon

I was wondering whether or not [Brzozowski derivatives[(https://en.wikipedia.org/wiki/Brzozowski_derivative) are used / considered in this library?

**Comment by suhr** [comment]
By the way, my lexer is already useful: https://github.com/suhr/sana. It is not as fast as Logos though.

An important thing if you consider implementing something similar: don't compute derivative classes recursively. The join operation is associative, so you can compute it from a flat list which is much more efficient.

That's how it's done in Sana: https://github.com/suhr/sana/blob/master/sana_core/src/regex.rs#L546
