### ISSUE TITLE
Adding support for mixed case tokens

### ISSUE THREAD

**Issue by kirillbobyrev** [maciejhirsz/logos#177]
In some languages keywords are allowed to have mixed case, e.g. in SQL all of `SELECT`, `select` and `SeLeCt` will be (unfortunately) valid. Doing

```rust
#[token("SELECT")]
#[token("select")]
```

Will deal with the first two, but unfortunately it will still not be possible to parse mixed case keyword. Regexes are also not helping much here since it would have to be a case-insensitive regex. It would be great if it was possible to support mixed-cased tokens out-of-the-box.

**Comment by Protowalker** [comment]
Try `#[regex(r"(?i)select")]`. I'm not sure if it's supported in the regex library logo uses, though.

**Comment by kirillbobyrev** [comment]
@Protowalker oh, actually I started looking into regexes but then for some reason I though it wouldn't be possible with them.

This works, my bad, thank you very much for the answer!

**Comment by riederm** [comment]
is there a performance penalty when using the regex over the two tokens?
