### ISSUE TITLE
Confusing error with nonliteral explicit discriminant

### ISSUE THREAD

**Issue by CAD97** [maciejhirsz/logos#192]
https://github.com/maciejhirsz/logos/blob/ea0a3a7c2798144887243f1c535f332682091255/logos-derive/src/lib.rs#L67-L75

If a user sets a discriminant to a nonliteral expression such as `u16::MAX`, this fails with "attempt to add with overflow," which is far from indicative of the actual issue.

Instead of `.unwrap_or(usize::max_value())`, we should match the attempted evaluation, and in the case of an expression we cannot evaluate, emit a descriptive error that we don't support nonliteral explicit discriminants.

---

Side note: I think this handling is incorrect. IIUC, `Token::SIZE` should always be one larger than the largest discriminant. This is, however, demonstrably false:

```rust
enum Token {
    #[error]
    Error = 100,
    A, // = 101
    B, // = 102
}

fn main() {
    dbg!(Token::SIZE);
    dbg!(Token::B as usize);
}
```

gives `Token::SIZE = 101` and `Token::B as usize = 102`.

The simple fix here is tracking the "implicit discriminant" and checking that, rather than only the explicit discriminant.

However, it seems that `lookup!` is now completely unused by logos's internals. As such, I think the better recommendation is to remove `lookup!` and `Logos::SIZE`, and suggest users of `lookup!` use a crate such as [enum-map](https://lib.rs/crates/enum-map) instead.

**Comment by maciejhirsz** [comment]
Good find!
