### ISSUE TITLE
Feature request: allowing ignoring case in tokens

### ISSUE THREAD

**Issue by gymore-io** [maciejhirsz/logos#196]
Being able to do something like that would be neat.

```rust
#[token("hello", ignore_case = true)
Hello,
```

Does an equivalent to this already exist? Would it be a good first issue? (I would like to try and implement it :) )

**Comment by maciejhirsz** [comment]
I'd go for just `#[token("hello", ignore_case)]`.

It's all contained in the [proc macro here](https://github.com/maciejhirsz/logos/blob/aaa65727c71adc03e9f62e4f9c789160a4fbcb42/logos-derive/src/parser/mod.rs#L143), should be straight forward to mutate the definition given the flag, one thing to keep in mind is that this will have to work with both `token` and `regex` attributes.

**Comment by gymore-io** [comment]
I started to think about the implementation but I'm running in a little issue here:

How do we discriminate between `ignore_case`, a lone ident and `ignore_case` a callback function in first position? Do I filter certain keywords `parse_callback` ?

A way to fix this issue without needing to think about callbacks may be to change the syntax into something like

```rust
#[token, ignore(case)]
Hello,
```

and just treat `ignore(case)` into a `Nested::Named("ignore", NestedValue::Group("case"))`.

Also, unrelated to the issue: would a `ignore_ascii_case` variant be useful ? Only checking ascii case is much faster may preferred in most case.

The previous syntax could also be used with this variant.

```rust
#[token, ignore(ascii_case)]
```

But I will be honest, I still prefer the "flag" version, with just `#["hello", ignore_case]`.

Any thought about that?

**Comment by maciejhirsz** [comment]
Ah, you are right, a bare name assumes it's a function ref. `ignore(case)` and optionally `ignore(ascii_case)` sound good to me.

**Comment by gymore-io** [comment]
#198 merged
