### ISSUE TITLE
Is there an iterator ??

### ISSUE THREAD

**Issue by rdearman** [maciejhirsz/logos#206]
I want to do something like:

```
    for elem in lex.next()
    {
        println!("{:?}", elem);
    }
```

but it only returns one value? I'm very new to this, so not sure how to accomplish this.

It would be nice if there were some simple examples for beginners. For example something along the lines of taking "ADD 4 5" and outputing "4 + 5 = 9"

**Comment by maciejhirsz** [comment]
```rust
for elem in lex {
    println!("{:?}", elem);
}
```

Without the `.next()`. Rust implements an interator for any `Option<T>`, that's why iterating over the result of `next` gives you one result.

**Comment by rdearman** [comment]
Perfect. Thanks.
