### ISSUE TITLE
Get value of token

### ISSUE THREAD

**Issue by rdearman** [maciejhirsz/logos#207]
I apologize for using issues for support. But don't know where else to get assistance.  I get an error on #[derive(Logos, Debug, PartialEq)] When I reference the function inside of the Token I get the error:

```
6 | #[derive(Logos, Debug, PartialEq)]
  |          ^^^^^
  |          |
  |          expected struct `String`, found `()`
  |          expected due to this
```

```
#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[regex("(bl[[:space:]]+[[:word:]]+)", bl_jmp, priority = 1, ignore(ascii_case))]
    BL,
}

fn bl_jmp(lex: &mut Lexer<Token>) -> String
{
    let slice = lex.slice();
    let myString:String = slice[..slice.len()-1].to_string();
    println!("FROM FUNCTION: {:?}", myString);
    return myString;
}
```

If I remove the reference to the bl_jmp function it will compile, but I want to get the value. I've attached my program and my test file (as text) for reference. 

[main.rs.txt](https://github.com/maciejhirsz/logos/files/6132846/main.rs.txt)

[tester.s.txt](https://github.com/maciejhirsz/logos/files/6132848/tester.s.txt)

**Comment by maciejhirsz** [comment]
There is no field in your enum variant for the value to be stored into, just turn `BL,` into `BL(String),` and it should click. That error could have been more user friendly, although that part is handled by generics rather than the macro internals so there isn't that much I can do to improve it atm.

**Comment by rdearman** [comment]
Thanks!
