### ISSUE TITLE
Can't pass string 

### ISSUE THREAD

**Issue by rdearman** [maciejhirsz/logos#209]
How do I pass the Token's String to a function? I put a small snippet below. It does the match, then correctly passes it over to the "lcaseit" function which lower cases the string. Later I want to go through all of the matching Tokens and pass the string to a function. But elem.to_string() doesn't exist. But the println! macro works. 

Is there a way to convert to a string, or do I need to do everything in the first function call?

```
    #[regex("[[:space:]]+bl[[:space:]]+([[:word:]]+)",lcaseit, priority = 1, ignore(ascii_case))]
    BL(String),

===

        let lex = Token::lexer( tline );
        for elem in lex
        {
            match elem
            {
                Token::BL(_)  => println!("{:?}", elem),
```

**Comment by maciejhirsz** [comment]
`Token::BL(inner)  => println!("{}", inner),`

**Comment by rdearman** [comment]
Perfect! Thanks.
