### ISSUE TITLE
Whitespace envangelism

### ISSUE THREAD

**Issue by CAD97** [maciejhirsz/logos#21]
From experimentation I was able to determine that the bytes `[\x01-\x20]` are treated as whitespace by the derive.

Personally, I'm a fan of (at least being able to) [including whitespace in the token stream](https://github.com/rust-analyzer/rowan/blob/master/examples/s_expressions.rs#L26), so it's good that I can then write a `#[regex = r"[\x01-\x20]+"]` which then maps each string of whitespace to a produced token.

Of course, [that's not all of the whitespace characters](https://github.com/CAD97/pest-unicode/blob/master/pest/White_Space.pest), and it's not like there's [just one](https://github.com/CAD97/pest-unicode/blob/master/pest/Pattern_White_Space.pest) accepted [set of whitespace](https://github.com/CAD97/pest-unicode/blob/master/pest/Separator.pest).

"ASCII whitespace" is a good default, but should probably be configurable, and support non-ASCII whitespace as well. I think the best way to handle silent whitespace would be to treat it as a "virtual token"; it goes through the normal token matching process, but gets handed off to the `Extras` instead of emitted (unless devirtualized). Logos could also just take a stance of putting whitespace in the stream, and then expecting the consumer to filter it out if desired.

**Comment by maciejhirsz** [comment]
Alright, 0.10 finally has full support for changing default whitespace behavior including support of unicode whitespace characters. [Test](https://github.com/maciejhirsz/logos/blob/d0c140aa59c58b838c8814075b67a27b279b0587/tests/tests/whitespace.rs#L4).

Will try to make a release within next 2 days!
