### ISSUE TITLE
How can I lex indents and dedents using logos?

### ISSUE THREAD

**Issue by AbooMinister25** [maciejhirsz/logos#212]
Hey, so I'm writing a language using Rust, and I'm using logos as the lexer. My language uses indentation to show blocks, and I can't figure out on how to lex indents and dedents using logos. I'm pretty sure I'll need to keep track of the indents on an indent stack, but I'm not sure how to do it with logos.

**Comment by UnexDev** [comment]
I know I'm three years late, but do you happen to have the solution you found, @AbooMinister25?

**Comment by jeertmans** [comment]
Probably using callbacks @UnexDev and storing the current indentation level using some Extra (see the book)?

**Comment by aricursion** [comment]
DOes anyone have any examples of this working? That would be super cool
