### ISSUE TITLE
Logos skip last 2 chars in source

### ISSUE THREAD

**Issue by ryangjchandler** [maciejhirsz/logos#215]
I'm using Logos to parse out some PHP code. I'm grokking the crate a little bit by using the `Error` token variant to handle any arbitrary text found outside of the `<?php ?>` tags since there's no intelligent way to handle this with RegEx (that I can think of).

The issue is that it seems to be ignoring the last 2 characters in the source... if I add 2 line breaks to the end, it picks it up find but won't return an `Error` variant for those line breaks either.

<img width="807" alt="CleanShot 2021-06-14 at 19 41 19@2x" src="https://user-images.githubusercontent.com/41837763/121942574-8bb27580-cd48-11eb-9026-00f53e2fca5f.png">

**Comment by maciejhirsz** [comment]
Can't really help much without code example of what you are doing. Either way, it sounds like you should be using two separate lexers, and `morph` between contexts when you exit php context.

**Comment by ryangjchandler** [comment]
@maciejhirsz Yeah, I've updated my code to use `morph` after RTFM lol. Thanks for the response though!
