### ISSUE TITLE
Not supporting look-arounds in Regex.

### ISSUE THREAD

**Issue by Icylla** [maciejhirsz/logos#218]
Logos is currently using the regex crate, which doesn't support look-arounds. A crate like fancy-regex could be used to add support for look-arounds 

fancy_regex - https://crates.io/crates/fancy_regex

**Comment by maciejhirsz** [comment]
> Logos is currently using the regex crate

It doesn't. Logos is using `regex-syntax` for syntax alone, and it only implements a subset of regular expressions to prevent performance issues like backtracking when lexing (which lookarounds would need).

**Comment by Icylla** [comment]
I apologize for the misunderstanding 👍🏻 

I will close this issue now.

**Comment by maciejhirsz** [comment]
No worries, it's on me for still not having this documented properly :see_no_evil:.
