### ISSUE TITLE
More first-class non-ASCII support

### ISSUE THREAD

**Issue by CAD97** [maciejhirsz/logos#22]
Such as

- matching properties `\p{WSpace}` and
- non-ASCII ranges `[\u100-\u200]`.

Converting arbitrary ranges of Unicode codepoints to the appropriate utf8 bytewise matcher can be done through [utf8-ranges](https://crates.io/crates/utf8-ranges) and properties into codepoint ranges by [ucd-generate](https://crates.io/crates/ucd-generate). Both tools are used by the `regex` crate for their support of said regex features.

I'm experimenting with some different things around parser and lexer generation currently, and I'd love to use Logos as my lexer backend (at least in compiled mode), but support of Unicode property sets limits me to other solutions (abusing `RegexSet`) for the time being.

**Comment by maciejhirsz** [comment]
`utf8-ranges` looks really cool! I've been thinking about checking if a range is non-ASCII and then reading a full `char` from source, but that would have some side effects on performance (non-uniform bumping of the index). I'll definitely give this a go!

**Comment by maciejhirsz** [comment]
This has been way easier to implement than I initially thought, and having that Cyrillic test pass makes me very happy. Thanks again @CAD97 for the suggestion and @BurntSushi for the excellent crate!

Matching properties should be pretty straight forward now!

**Comment by maciejhirsz** [comment]
Turns our properties are so straight forward, they are already working since `regex_syntax` handles them for me :nerd_face:.
