### ISSUE TITLE
Feature: allow `Option<Skip>`, `Result<Filter<T>, _>` in callbacks

### ISSUE THREAD

**Issue by Jeremy-Stafford** [maciejhirsz/logos#235]
Currently, logos does not allow nesting `Skip` and `Filter` in `Option` or `Result`. 

This makes the following pattern very difficult (impossible?) to express:
* Match a "start" pattern.
* Compute the number of characters to skip, raising an error if this is not possible.
* Match a "end" pattern.
* Skip the whole token.

This pattern appears when lexing C-style block comments (`/* ... */`). For languages which forbid nesting (including C itself), this can be done using a regex (read: unreadable mess of stars and slashes). For languages which allow nesting, this cannot be fixed.

The current callback-result system is implemented as a trait. It would therefore be impossible to allow `Option<Skip>` (that would introduce overlapping implementations). This feature would therefore require a type defined as

```rust
enum FilterResult<T> {
    Error,
    Skip,
    Ok(T),
}
```

**Comment by evbo** [comment]
@Jeremy-Stafford see this discussion too on C style block comments, there is a callback work around at a slight performance cost:
https://github.com/maciejhirsz/logos/issues/180#issuecomment-736401091

**Comment by evbo** [comment]
This is great because actually I can't seem to get `logos::skip` working _even for a comments regex_ (other regexes, e.g. whitespace work fine with `skip` though...):

```rust
#[regex(r"/\*([^*]|\**[^*/])*\*+/", logos::skip)]
// this won't skip content e.g.: 1,2,3 /* basic */
```

So I agree, there is no way to successfully ignore comments other than by performing a noop with a token:

```rust
#[regex(r"/\*([^*]|\**[^*/])*\*+/")]
Comment  // correctly identifies /* basic */ as a Comment token

// ...then in your parser just never add the Comment to the AST...
```

**Comment by evbo** [comment]
@Jeremy-Stafford thank you and the contribution you made to the docs is excellent! Works like a charm :)
