### ISSUE TITLE
Dealing with escaped quotes (`\"`, `\'`) in character and string literal tokens.

### ISSUE THREAD

**Issue by AshtonSnapp** [maciejhirsz/logos#238]
Somewhat self-explanatory. If someone creates a character (with single-quotes) or string (with double-quotes) literal with the corresponding quote type escaped, how can I ensure that Logos doesn't prematurely end the slice? For example, if someone has a string literal that looks like this: `"So your name is \"{}\"?"`, how can I ensure that Logos correctly lexes that string as `String("So your name is \"{}\"?")` instead of `String("So your name is \") Operator(Op::OpenCurly) Operator(Op::CloseCurly) Error String("?")`?

I understand that Logos uses a subset of regular expressions, meaning not everything is supported. Which is why I came here to ask this instead of using an online RegEx playground to try and figure it out (as any solution found there isn't guaranteed to work under Logos).

**Comment by pdogr** [comment]
Probably you could use something like 
```rust
#[regex(r#""(\\"|[^"\n])*""#]
Literal(String)
```

**Comment by ryangjchandler** [comment]
@AshtonSnapp You might find something useful here: https://github.com/maciejhirsz/logos/issues/133
