### ISSUE TITLE
Access extras on SpannedIter

### ISSUE THREAD

**Issue by hellow554** [maciejhirsz/logos#266]
There's the Extras item on the lexer, but there's no way to access that once you converted it to a `SpannedIter` via `Spanned`.
Would it be possible to add that to the `SpannedIter` as well?

**Comment by marcospb19** [comment]
Implemented by #231, but we don't know when it's going to be merged.

**Comment by marcospb19** [comment]
Very similar to #231, it's just missing the method to access this field.
