### ISSUE TITLE
Switching lexers

### ISSUE THREAD

**Issue by ronniec95** [maciejhirsz/logos#27]
Is there a way to switch lexers?
Standard case of lexing a buffer using a primary lexer and then a separate function to parse quoted strings, then switch back?

Is there an easy way to get the current position of the lexer and move it along while I take over?

**Comment by maciejhirsz** [comment]
_Maybe_. There is no way to do context switching on the `Lexer` atm, but you can do a lot with function callbacks. Have a look at [this piece of code from Lunarity](https://github.com/paritytech/lunarity/blob/39fb996eab248a0a4888b90748a7c8198a0722f9/lexer/src/token.rs#L419-L438), it handleds the block comments (`/* ... */`) by exposing the internals of the `Lexer` and basically doing the work manually.

On a sidenote, quoted strings [you can already do with regex](https://github.com/maciejhirsz/logos/blob/cd6691715d8f597b4a1956734e73a38a673a0cf8/tests/tests/advanced.rs#L16-L17). If you want the lexer to produce an unescaped `String` out of the literal, you can add a `#[callback]` there that reads through it and stores the result on some fields on [`Extras`](https://github.com/maciejhirsz/logos/blob/cd6691715d8f597b4a1956734e73a38a673a0cf8/tests/tests/simple.rs#L8-L30).

**Comment by jeertmans** [comment]
Closing this a too old, feel free to re-open if needed.
