### ISSUE TITLE
[Question] How to deliminate seperators for a programming language

### ISSUE THREAD

**Issue by LyndonAlcock** [maciejhirsz/logos#271]
I am looking to add functions to my currently barren lexer however
`

    #[regex("[a-zA-Zα-ωΑ-Ω]+(")] // this does not work
    FuntionIdentifier,
    
    #[token("("|")")] // this also does not work
    Seperator

    #[regex("(|)|{|}", |lex| lex.slice().chars().next())] //this also doesn't work
    Seperator(char)
}
`

**Comment by Viphor** [comment]
First off.. Why would you want to add the parsing of a function in your lexer? Wouldn't it be a better fit in your AST generation/parsing step? (so when a function in your AST would be `IDENTIFIER LEFT_PARENTHESIS [PARAMS]* RIGHT_PARENTHESIS BODY`) This would also allow you to have ignored spaces between your identifier and starting parenthesis, as opposed to what you have in the first part.

Secondly, you should be able to do what you are trying with `#[regex("[(){}]")]` (if I remember correctly) or if you want the char, then add the lambda that you are doing in the last line.

Hope this makes sense. If I missed anything, please let me know. :)

**Comment by LyndonAlcock** [comment]
Thank you very much, that has cleared a lot of doubts
