### ISSUE TITLE
Is it possible to lex grammars with semantic whitespaces?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [maciejhirsz/logos#276]
For examples Python or Haskell?

As far as I can tell, for examples, `tree-sitter` allows special handling for whitespace https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners

**Comment by maciejhirsz** [comment]
Yes. Just don't define skip for the whitespace (`#[regex(r"[ \t\n\f]+", logos::skip)]` currently) and parse whitespace as tokens, or do something else with `Extras` [like in this tests scenario](https://github.com/maciejhirsz/logos/blob/56afbaa6667dc74faea202ab6e8a43e18d3775ad/tests/tests/simple.rs#L5-L35).
