### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by adam-becker** [maciejhirsz/logos#280]
I'd like to use this library for a personal project, but it seems like no development is happening anymore. Is this the case?

**Comment by jeertmans** [comment]
Hi! I have recently send a message to the author of Logos and he replied that he was taking a quite long sabbatical break

**Comment by adam-becker** [comment]
That's too bad, guess I'm hand-rolling the tokenizer then. Thanks!

**Comment by maciejhirsz** [comment]
I suppose I can close this as of today :upside_down_face:.
