### ISSUE TITLE
No way to find a string

### ISSUE THREAD

**Issue by Ghostdev84** [maciejhirsz/logos#281]
there is no regex to find a string

**Comment by jeertmans** [comment]
Could you elaborate your problem?
What do you mean by a « string » ?

**Comment by Ghostdev84** [comment]
Data type String

**Comment by jeertmans** [comment]
Sorry, but you need to be more precise.

Please give an example of what you are trying to achieve.

**Comment by maciejhirsz** [comment]
Here is a test pattern that matches JavaScript strings:
https://github.com/maciejhirsz/logos/blob/51c1f8c1bca990758e05c5600becc6d9c10bd6e4/tests/tests/advanced.rs#L12-L13

You can see in tests it's passing, handling escaped quotes correctly.
