### ISSUE TITLE
How to implement a fallback token variant in 0.13.0?

### ISSUE THREAD

**Issue by shilangyu** [maciejhirsz/logos#299]
Perhaps not a "issue" topic, but discussions which would be more appropriate here are not enabled for this repo.

I use logos as a way to losslessly tokenize a programming language. Since the lexer should always produce a full sequence of tokens, I used the v0.12.x `#[error]` token variant as a "catch all" for unmatched text. This is important, as I never want to bail on invalid text, some compiler error is later emitted for such error tokens. Simplified example:

```rs
#[derive(Logos, Copy, Clone, Debug, PartialEq, Eq)]
pub enum Token {
    #[token("if")]
    If,
    #[token("while")]
    While,
    #[regex("[a-zA-Z][a-zA-Z0-9]*")]
    Ident,
    #[regex(r"[ \t]+")]
    Whitespace,
    #[error]
    Error,
}
```

In 0.13.0 the lexer emits `Result`s. How can I achieve a similar behavior? My first thought was to just move the `Token::Error` variant to a `Logos::Error` using `#[logos(error = MyError)]` and then when iterating over the `Result`s just map `Result::Err` to my `Token::Error`. But I do not see any way to preserve text/span information in custom errors, which is very important. Of course, one could also literally do a catch all with:

```diff
#[derive(Logos, Copy, Clone, Debug, PartialEq, Eq)]
pub enum Token {
    #[token("if")]
    If,
    #[token("while")]
    While,
    #[regex("[a-zA-Z][a-zA-Z0-9]*")]
    Ident,
    #[regex(r"[ \t]+")]
    Whitespace,
+   #[regex(".+")]
-   #[error]
    Error,
}
```

But I see two problems here. First, the lexer would still emit `Results`, even though in practice everything will be a `Result::Ok`, I would hate to have to `unwrap` everything. Second, I wouldn't really trust `".+"` never taking precedence over some other tokens.

What would be an appropriate migration strategy for such a usecase?

**Comment by maciejhirsz** [comment]
> But I do not see any way to preserve text/span information in custom errors, which is very important. Of course, one could also literally do a catch all with:

This hasn't have changed, if `lex.next()` produces `Some(Err(_))` then `lex.span()` will give you a range for that error, and `lex.slice()` will give you slice of the source for that error.

**Comment by shilangyu** [comment]
> This hasn't have changed, if `lex.next()` produces `Some(Err(_))` then `lex.span()` will give you a range for that error, and `lex.slice()` will give you slice of the source for that error.

Riiiight, indeed.

> If you put `#[regex(".+")]` then no matter what source you give it, the entire source will just lex as one of that token, so I wouldn't advise it.

Oh, I assumed the "Specific beats generic" rule would win against the "Longer beats shorter" rule.


So in the end I migrated this way:

- remove `#[error]` above the error token variant
- add `.unwrap_or(Token::Error)` when iterating over the logos lexer

All tests pass and no performance regressions were found! Thanks for the help.

**Comment by maciejhirsz** [comment]
> Oh, I assumed the "Specific beats generic" rule would win against the "Longer beats shorter" rule.

I think this wording is causing a lot of confusion. It's the **longer pattern beats shorter pattern**, e.g.: `#[token("foo")]` (3) is longer than `#[regex("[a-z]+")]` (1+) and therefore has higher priority by default. Priority only applies when there is ambiguity, if there is just one possible longest match there is no ambiguity (see discussion in #297).
