### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Boscop** [maciejhirsz/logos#305]
Thanks for making this crate, it seems very useful in combination with chumsky :)

Is there a changelog somewhere, e.g. what changed between 0.12 and 0.13?

(This example still uses 0.12: <https://github.com/zesterer/chumsky/blob/main/examples/logos.rs>)

**Comment by jeertmans** [comment]
Hello @Boscop!

This release changes are documented here https://github.com/maciejhirsz/logos/releases/tag/v0.13.

Hope it helps :-)

**Comment by Boscop** [comment]
Ah thanks. I was trying to find a CHANGELOG.md file, and the search also didn't show anything when searching for "changelog"..
