### ISSUE TITLE
How do I specify to glob the rest of the input?

### ISSUE THREAD

**Issue by mscofield0** [maciejhirsz/logos#306]
Using `#[regex(r".+")]` just triumphs all the other inputs in terms of priority for me for some reason, is there a way I can just specify that is should match until the end of the input?

**Comment by jeertmans** [comment]
Hello, you should read #302 and this associated PR, as this boils down to the same issue :)

**Comment by mscofield0** [comment]
@jeertmans so basically, find a character that you won't ever use and then match against everything that *isn't* that?

**Comment by jeertmans** [comment]
If you have some sort of terminating char, yes.

You what you want is to match everything, then you are better handling that case during the iteration on tokens.

**Comment by mscofield0** [comment]
What if I don't have any terminating char, is there a better way?

**Comment by jeertmans** [comment]
What do you mean? You want to match everything until the end of your string ?

**Comment by mscofield0** [comment]
Yeah

**Comment by jeertmans** [comment]
Well then you could use a custom callback, or even manually stop the iterator using something like a filter to avoid useless computation

**Comment by mscofield0** [comment]
Can you show some code?

**Comment by jeertmans** [comment]
Can you first show me the tokens you are trying to create? So I can modify your code from that

**Comment by mscofield0** [comment]
```rust
#[derive(Logos, Debug, PartialEq)]
#[logos(skip r"[ \t\r\n\f]+")]
enum Token {
	#[regex(r"([a-zA-Z]*\.)*[a-zA-Z]*", priority = 1)]
	Module,

	#[regex(r"::[a-zA-Z]+()")]
	Function,

	#[token("|")]
	Separator,

	#[regex(r"[0-9]+-[a-zA-Z]+")]
	TraceId,
	
	#[regex(r".+", priority = 0)]
	Context,
}
```

**Comment by jeertmans** [comment]
Hum I might need some more context before I can help you 😅

do you have an example string where you can highlight parts you would like to be matched by each token?

**Comment by mscofield0** [comment]
Yeah, of course:
belot.endpoint::ws() | 1248918498-azfa | some logging information here
^^^^^^^^^^^^^^^^^^^^ ^ ^^^^^^^^^^^^^^^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|                    | |               | |
\ Module             \_|_ Separator    / \ Context
                       |
                       \ <timestamp>-<4-char-random-string> aka the "TraceId" token

**Comment by jeertmans** [comment]
Hello @mscofield0, sorry for the late reply! I think this will never be possible to implement with Logos, since we try to avoid this kind of "match all" regexes.

In your very application, you are just better off looking for an error when parsing (meaning none of your tokens match) and then just take the remainder of the slice as context.
