### ISSUE TITLE
Recursive regex or equivalent

### ISSUE THREAD

**Issue by thetayloredman** [maciejhirsz/logos#307]
My use case is to match C-style block comments *with nesting.* That would look something like: `/* /* ... */ */` being skipped.

I can't find away to use recursive regex, likely as the `regex` crate doesn't support them, but either way, is there an option to provide a callback or something to dynamically skip tokens?

**Comment by jeertmans** [comment]
@thetayloredman yes you could use a callback function that consumes all the tokens until some end token is matched. Logos provides support for callbacks.

**Comment by thetayloredman** [comment]
> @thetayloredman yes you could use a callback function that consumes all the tokens until some end token is matched. Logos provides support for callbacks.

So `#[token("/*", |...| { /* ... consumes the rest of the comment... */; logos::Skip })]`?

**Comment by jeertmans** [comment]
I don’t think you'd need the skip directive here

**Comment by thetayloredman** [comment]
> I don’t think you'd need the skip directive here

well, I'd want the comment not to show up in the lexer output at all

**Comment by jeertmans** [comment]
You could have the callback function return a Filter (or FilteResult), see https://docs.rs/logos/latest/logos/enum.Filter.html

**Comment by thetayloredman** [comment]
> You could have the callback function return a Filter (or FilteResult), see https://docs.rs/logos/latest/logos/enum.Filter.html

I'm not quite sure I'm understanding

I was assuming I would be basically telling Logos to "when we see `/*`, call my callback and it will consume all tokens until a point, at which point it simply discards all of those tokens"

In psuedocode:

```rust
#[token("/*", |lex| {
    // keep scanning until we see "*/"
    for char in lex.chars() {
        if char == "*" && lex.peek() == "/" {
            break;
        } // otherwise continue consuming
    }
    // imagining this input:
    // a /* b c */ d
    // -----------|
    //            ^ current index
    // this rule needs to return some token, but we simply
    // want to skip that comment and produce nothing
    logos::Skip
})]
```

**Comment by jeertmans** [comment]
Hum yes, sort of, but Lexer does not have `chars` nor a `peek` method (I think). So you better create another `#[token("*/")]` and call `lex.next()` until reaching `"*/"`.

**Comment by thetayloredman** [comment]
What if the lexer reaches something within the comment that's not a token? This should still lex:

```
/* "abc */
```

However, assuming I keep iterating, it might not reach the `*/` because it's scanning a string literal.

Is this a use case for morphs?

**Comment by jeertmans** [comment]
Then the lexer will return an error, which you can silently ignore if you are in your comment block.

i think so but I have never user morph myself

**Comment by thetayloredman** [comment]
> Then the lexer will return an error, which you can silently ignore if you are in your comment block.
> 
> i think so but I have never user morph myself

The lexer isn't able to return an error if it's still looking for the end of that token I assume..?

**Comment by thetayloredman** [comment]
> i think so but I have never user morph myself

I'd like to try using morphs to keep the token type enum clean -- is it possible to make the callback take an *owned* Lexer that's not cloned and pass ownership back when its done?

**Comment by jeertmans** [comment]
Good to know you have found a solution :D
