### ISSUE TITLE
Keep track of line number and column

### ISSUE THREAD

**Issue by sudochop** [maciejhirsz/logos#308]
Is there a simple way to do this via the provided api? I suppose using the `slice()` gives you the position of the token, but then you'd have to loop back over the entire string and start re-doing some of the lexing work to figure out whitespace characters and translating that to line/column offsets.

**Comment by jeertmans** [comment]
Hi! To me, the simplest way is to create a token that matches newlines, and count + 1 every time you encounter one token of this kind. For the line offset, you just do it when needed.

That’s good if you only need to compute the line position when you find an error and want to report the position of that error.

If you want your tokens iterator to contain the position of each token, then you might consider adding some internal state to your lexer. For this, use Extras.

**Comment by jeertmans** [comment]
Hey @sudochop, if you are comfortable reading PR, I made one that adds an example using Extras, that should probably help you: https://github.com/maciejhirsz/logos/pull/309/files

**Comment by sudochop** [comment]
Thank you for the example - that's very helpful! Any thoughts on how to incorporate something like [codespan](https://github.com/brendanzab/codespan)?

**Comment by jeertmans** [comment]
In this example I used a similar tool: https://github.com/maciejhirsz/logos/blob/book/logos/examples/json.rs

This library automatically compute the line number here :)

**Comment by sudochop** [comment]
Exactly what I was looking for. Thanks so much!
