### ISSUE TITLE
fix(ci): Github pages deployment

### ISSUE THREAD

**Issue by jeertmans** [maciejhirsz/logos#310]
Hello @maciejhirsz,

This is a small issue to list things you need to do to make GitHub pages deployment work (they fail for the moment).

- [x] Allow deploying from Actions (https://github.com/maciejhirsz/logos/settings/pages) 
![image](https://github.com/maciejhirsz/logos/assets/27275099/8e9585c1-23c8-492c-bf61-b93e3949ec9a)

- [x] Add a branch protection rule named `github-pages` (https://github.com/maciejhirsz/logos/settings/environments) 
![image](https://github.com/maciejhirsz/logos/assets/27275099/89380706-08e4-4a39-b3fe-fc9aa60dd731)

- [x] Add all the branches you'd like to allow the pages to be deployed from. I recommend `book` and `master` for the moment. 
![image](https://github.com/maciejhirsz/logos/assets/27275099/3325f6dd-222b-4f85-b641-a36804c09a76)

- [x] #304 needs to be merged because it fixes a path issue for uploading artifacts.

I'm using a custom domain, so you can see how the `book` branch is rendering on my website: https://eertmans.be/logos/.

If you do not have a custom domain attached to your GitHub account, it will probably be available on https://maciejhirsz.github.io/logos.

**Comment by maciejhirsz** [comment]
@jeertmans everything should be fixed now, it might need another PR to actually trigger the action now I think?

**Comment by jeertmans** [comment]
You can actually manually trigger the action with a « Workflow dispatch ». So in the actions tab of you repo, go to the action and run it on the book branch :)

**Comment by maciejhirsz** [comment]
I merged another PR and it went through: https://maciejhirsz.github.io/logos/ 🎉

Gonna get a custom domain for this later, cheers!

**Comment by jeertmans** [comment]
Nice! It looks great!

**Comment by jeertmans** [comment]
Yeah, domain names can be quite expansive ^^'!

Anyway, you can notice that https://maciejhirsz.github.io/logos/ will also still work, and redirect to your new domain. So it's safe to keep using https://maciejhirsz.github.io/logos/ on links that are not "directly exposed" to the user, so that they never break.

This is what I do for my projects :-)
