### ISSUE TITLE
Order of token determination?

### ISSUE THREAD

**Issue by ethindp** [maciejhirsz/logos#312]
So, I'm working on building a CST. However, that means tokenizing *every* character in the input (not just those I'd need for parsing). So, I'm curious: if I have -- say -- a Unicode class rule matching separators in my language (or, in my case, two of them, specifically `[&-/:->@\[\]|]` and `(?:\*\*|\.\.|[/:]=|<[<->]|=>|>[=>])`), but I then have an expression matching all punctuation characters in Unicode (`\pP`), does the first set of regex take priority over the `\pP` one, or do I have to make exceptions?

**Comment by jeertmans** [comment]
Hello!

Did you check the rules mentioned on this page?

https://logos.maciej.codes/token-disambiguation.html

**Comment by ethindp** [comment]
@jeertmans I just remembered this, thanks.
