### ISSUE TITLE
`?` doesn't work correctly

### ISSUE THREAD

**Issue by rep-nop** [maciejhirsz/logos#32]
While trying to parse numbers with a regex, @cryze found a bug with the regex compiling:
```rust
#[regex = "-?[0-9]+"]
NumericLit,
```

this will only parse negative numbers and rejects positive ones. I was able to reproduce it with that above code.

**Comment by rep-nop** [comment]
Also tried a few variations using `?` but couldn't seem to get it to work.

**Comment by maciejhirsz** [comment]
Hey, thanks for reporting this! There is some special logic around the first byte of the pattern that is likely breaking down here, it should be easy to fix.

If you want a temporary workaround before I fix it, `#[regex = "(-[0-9]+|[0-9]+)"]` should work fine and have the same performance characteristics.

**Comment by maciejhirsz** [comment]
Released 0.7.4 with a fix for this. [Added a test](https://github.com/maciejhirsz/logos/blob/8f4eec2e0cb0f682871713a675eb812067cd2381/tests/tests/advanced.rs#L22-L23) for this scenario, should it shouldn't regress in the future.

**Comment by rep-nop** [comment]
Awesome, thank you so much. Awesome crate :+1: :D
