### ISSUE TITLE
Publishing a related crate

### ISSUE THREAD

**Issue by Rafaeltheraven** [maciejhirsz/logos#326]
Hey there, I've recently started using Logos and really like it. In order to do nicer error handling for my parser, I've created a procedural macro which uses the `token` on a `Logos` enum to implement the `Display` trait automatically.

I would now like to publish this crate, but the obvious name of `logos_display` feels wrong because it seems to imply an official connection with the `logos` crate, even though there isn't. Do the maintainers of logos have any desires R.E. publishing third-party logos related crates?

**Comment by jeertmans** [comment]
Hello! Do you have some public repository on which we can see your crate?

And maybe some example usage of it? :-)

**Comment by Rafaeltheraven** [comment]
Quickly pushed it to `https://github.com/Rafaeltheraven/logos_display`, including a readme with examples. 

There's no tests at the moment because I didn't feel like dealing with the proc_macro headache that entails :P

**Comment by jeertmans** [comment]
nice! How does it deal with regexes or multiple tokens for the same variant?

**Comment by Rafaeltheraven** [comment]
Explained in the README. If there is no `token` attribute, it just uses the name of the variant. If there are multiple tokens for the same variants they are concatenated with `/`. In all cases, you can use the `override_display` attribute to manually specify a string representation.

**Comment by Rafaeltheraven** [comment]
Then I'll probably stick to `logos-display`.

I considered support for regex attributes, but since the language a regex can accept is potentially infinite, the only representation that makes sense is just copy-pasting the regex itself. This is trivial as a default implementation, but it isn't very readable and I thought that using the variant name and override as needed would be the more common use-case (as it would just say I.E `LitString` as opposed to `\$\(([^\)\\]|\\.)*\)`). 

I agree that a more modular approach to how concatenation works is a good idea though, which is partly why I haven't published the crate yet.

**Comment by jeertmans** [comment]
In my opinion, displaying the raw regex string is fine, as people are more likely to use it as a debugging tool.

**Comment by Rafaeltheraven** [comment]
I've published the crate with the name `logos-display` (https://crates.io/crates/logos-display) so I'll close this issue now.
