### ISSUE TITLE
Help needed: matching Python-like multiline strings

### ISSUE THREAD

**Issue by elenakrittik** [maciejhirsz/logos#330]
Every single regex i could find uses either globals flags or lookaround, neither of which are supported by logos (to my knowledge, at least). Syntax like `[^(""")]` (NOT group of symbols) is not supported by regex itself, though even if it was i'm pretty sure it'll fall into the lookahead category and therefore would still not be supported by logos. CAD97's C-style block comment regex is pretty much incompatible with Python-like block comments, where comment start and comment end are all the same characters. I imagine this can be possible with a lot of boilerplate around extras, or via postprocessing, but before going with these i'd like to ask if anyone encountered the same problem and got a solution. Any help is greatly appreciated!

**Comment by jeertmans** [comment]
Hello! I am afraid it is not possible by just using regexes. This is a bit the limitation of not using look-around and so on: you gain performances at the cost of fewer features. But I think it's relatively easy to implement a callback function with `Extras` that handle triple quotes.

**Comment by hyperswine** [comment]
> Hello! I am afraid it is not possible by just using regexes. This is a bit the limitation of not using look-around and so on: you gain performances at the cost of fewer features. But I think it's relatively easy to implement a callback function with `Extras` that handle triple quotes.

can you give an example?

**Comment by elenakrittik** [comment]
I haven't done that yet, but it seems like using a sublexer (see #61) for this would be the best way.

**Comment by jeertmans** [comment]
Closing, See https://github.com/maciejhirsz/logos/issues/421#issuecomment-2348285243 for an example on comments (which is very similar to multiline strings).
