### ISSUE TITLE
`SpannedIter` doesn't implement `Clone`

### ISSUE THREAD

**Issue by T0mstone** [maciejhirsz/logos#331]
You can clone a `Lexer`, so I'd expect `SpannedIter` to also be cloneable.

**Comment by jeertmans** [comment]
Indeed, feel free to open a PR to fix this issue :-)

**Comment by T0mstone** [comment]
Oh, just as I was about to do that, it seems it's already resolved on master, just not on crates.io yet.

**Comment by mcdearman** [comment]
It also doesn't implement Debug, which is even worse imo.
