### ISSUE TITLE
Issue with regex and newlines

### ISSUE THREAD

**Issue by cylewitruk** [maciejhirsz/logos#339]
Hi!
I'm trying to use regex's to match comments in the format `;;.*\n` but I keep getting the following error:
> #[regex]: ".+" and ".*" patterns will greedily consume the entire source till the end as Logos does not allow backtracking. If you are looking to match everything until a specific character, you should use a negative character class. E.g., use regex r"'[^']*'" to match anything in between two quotes. Read more about that here: https://github.com/maciejhirsz/logos/issues/302#issuecomment-1521342541.

That seemed weird to me so I came here and searched for issues regarding newlines, and came across some examples that others claim to be using in issues #124 and #133, which I also tried to no avail (same error).

I'm assuming that since those expressions have previously worked for others that this might be a regression? I have tried directly referencing the crate on github pointed to `master` as well.

**Comment by jeertmans** [comment]
Hello, as mentioned in the error message, did you try this pattern: `;;[^\n]*`?

Note, you can use `;;[^\n]*\n` if you want to match the newline.

**Comment by cylewitruk** [comment]
> Hello, as mentioned in the error message, did you try this pattern: `;;[^\n]*`?
> 
> Note, you can use `;;[^\n]*\n` if you want to match the newline.

I just tried both of your examples and both result in the same error. The regex in the error message, `'[^']*'`, does work, however, but there's no newlines in it. If I change the `\n`s to `\\n`s then it doesn't complain, but then we're not matching on newlines :)

**Comment by jeertmans** [comment]
Could you provide a MWE please?

**Comment by cylewitruk** [comment]
> Could you provide a MWE please?

Actually I managed to get it to work - I think it was because I had manually added the `logos_derive` crate when trying to figure something else out.  Removing it seems to have solved the problem :)

**Comment by jeertmans** [comment]
Nice, closing this then 👍
