### ISSUE TITLE
Where can I find the handbook?

### ISSUE THREAD

**Issue by abiriadev** [maciejhirsz/logos#342]
I apologize if this isn't the right place to ask this question.

I've come across many mentions of a 'handbook' in some issues, but I haven't been able to find any resource about it in docs.rs, the README, the entire codebase, and release notes.

Could anyone guide me on where to find it, if possible?

I am fairly new to `logos`, so a brief introduction material would be very helpful, especially for newcomers like me.

**Comment by jeertmans** [comment]
Hello @abiriadev, the handbook is hosted on GitHub pages, see: https://logos.maciej.codes/.

I hope it helps!

**Comment by abiriadev** [comment]
Thank you for letting me know!
