### ISSUE TITLE
Accessing `Logos`(token) inside a callback.

### ISSUE THREAD

**Issue by abiriadev** [maciejhirsz/logos#345]
Thanks for this wonderful crate!

I want to perform some comparison(with the last produced token) inside callbacks, so I need to access the `Logos`(the trait implemented for the `Token` struct here) from `Lexer`.

But it fails with an error like this:
```rs
#[derive(Debug, PartialEq, Logos, Clone)]
#[logos(
	skip r"[ \t]+",
	error = LexError,
	extras = Option<mem::Discriminant<Self>>
)]
pub enum Token {
	// error[E0616]: field `token` of struct `logos::Lexer` is private
	#[token("+", |lex| { lex.extras.insert(mem::discriminant(lex.token)); })]
	Plus,
	// ... other tokens
}
```

How can I achieve this? and is it safe to access a token from the callback, without consuming it?

I appreciate your help in advance! + I am willing to contribute if this is an issue and fixable.

**Comment by jeertmans** [comment]
Hello! Indeed, you cannot access `.token`.

I see two possible solutions:

1. Add a custom callback to each enum variant you would like to "keep memory of". E.g.,
   ```rust
   pub enum Token {
	   // error[E0616]: field `token` of struct `logos::Lexer` is private
	   #[token("+", |lex| { lex.extras.insert(mem::discriminant(Token::Plus)); })]
	   Plus,
	   // ... other tokens
   }
   ```
   I haven't tested this, and maybe it needs more tweaking.
2. Create a `Peekable` iterator and do post-processing to implement your function.

I don't think making `.token` public is a good idea, especially because of its complex type.

**Comment by abiriadev** [comment]
@jeertmans Thank you for your helpful answer.

I tried out your first suggestion and it appears to work as expected.

> I haven't tested this, and maybe it needs more tweaking.

It worked well, with the only modification being the addition of another enum. I'll write a full solution here for anyone who finds this issue page in the future for a similar problem.

1. Use `strum::EnumDiscriminants` to create a discriminant-only enum, since some tokens can own data (like identifier). This way, the `mem::Discriminant` is not needed anymore.
	```rs
	#[derive(Debug, Clone, PartialEq, Logos, EnumDiscriminants)]
	#[strum_discriminants(name(TokenKind))]
	#[logos(
		skip r"[ \t]+",
		error = LexError,
		extras = Option<TokenKind>
	)]
	pub enum Token {
		// ...
	}
	```
2. Add a callback with the corresponding `TokenType` for every variant I want to 'keep the memory of'. This is quite repetitive but can be automated by a macro later.
3. Implement a callback that performs comparison logic.
	```rs
	fn callback(lex: &mut Lexer<Token>) -> Filter<()> {
		let result = match lex.extras {
			Some(
				// identifiers
				| TokenKind::Identifier
	
				// literals
				| TokenKind::Integer | TokenKind::String
	
				// delimiters
				| TokenKind::RightAngledBracket
				| TokenKind::RightParenthesis
				| TokenKind::RightBrace
				| TokenKind::RightBracket,
			) => Filter::Emit(()),
			_ => Filter::Skip,
		};
		// ...
	}
	```

Thank you once again for your suggestion!

**Comment by jeertmans** [comment]
Nice, thanks for the descriptive solution!
