### ISSUE TITLE
Is it possible to print out unrecognized characters?

### ISSUE THREAD

**Issue by adder32** [maciejhirsz/logos#346]
I'm writing a tiny programming language and came across your crate.

I'm trying to report what characters were not recognized, that is, make the `Err` variant carry that information with it.

For example:

```rust
use logos::Logos;

#[derive(Default, Debug, Clone, Copy, PartialEq)]
enum SomeError {
    #[default]
    Other,
}

#[derive(Logos, Debug, Clone, Copy, PartialEq)]
#[logos(skip r"[ \t\n\f]+")] 
#[logos(error = SomeError)]
enum Token {
    #[token("print")]
    Print,
    
    #[regex(r"-?\d+(\.\d+)?", |lex| lex.slice().parse().ok())]
    Number(f64),

    #[token("+")]
    Plus,

    #[token(";")]
    Semicolon,
}

fn main() {
    let src = "print 1 + $ + 3;";
    let mut lex = Token::lexer(src);

    while let Some(m) = lex.next() {
        println!("{:?}", m);
    }
}
```

With this code, I get the following output:

```
Ok(Print)
Ok(Number(1.0))
Ok(Plus)
Err(Other)
Ok(Plus)
Ok(Number(3.0))
Ok(Semicolon)
```

What I'm trying to do is have the `Err` variant contain the unrecognized character -- `$` in this case.

Is this possible and/or easy to do?

Thanks.

**Comment by jeertmans** [comment]
Hello! Do you try accessing `lex.slice()`?

**Comment by jeertmans** [comment]
No problem :) glad it solved your problem!
