### ISSUE TITLE
Advice on how to implement format strings with logos

### ISSUE THREAD

**Issue by gavrilikhin-d** [maciejhirsz/logos#347]
Not an issue, but a question.

What's the best practice to tokenize format strings like `"hello to {name} from {name}"` with logos?

**Comment by jeertmans** [comment]
Well, if you only want to format using curly braces, you should have a least two tokens: the left `{` and the right `}` curly braces. Optionally, you can have a third token, e.g., `\`, if you want to be able to escape formatting. But this is not necessary, you can escape formatting by placing two consecutive curly braces, e.g., `{{`, like how Python does.

This all boils down to how you want your formatting rules to be.

For example, the author of this crate, @maciejhirsz, implement HTML templating with his project [ramhorns](https://github.com/maciejhirsz/ramhorns), which you can see a code snippet here: https://github.com/maciejhirsz/ramhorns/blob/02482cce0908d9f5b5888c805159655efb75b7d7/ramhorns/src/template/parse.rs#L19-L58
