### ISSUE TITLE
`[ -~]+` never matches

### ISSUE THREAD

**Issue by ivan770** [maciejhirsz/logos#350]
Hi!

I am unable to use regex `\[[ -~]+\]` in Logos for some reason, even though `regex` crate [works perfectly](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=eb81a85be569dfd3fea732dea6de227a) in this situation.

Example code:

```rust
#[derive(Logos, Debug, PartialEq)]
#[logos(subpattern printable_ascii = r#"[ -~]+"#)]
enum Token<'a> {
    #[regex(r#"\[(?&printable_ascii)\]"#)]
    Group(&'a str)
}

fn main() {
    let mut lex = Token::lexer("[Desktop Entry]");
    assert_eq!(lex.next(), Some(Ok(Token::Group("[Desktop Entry]"))));
}
```

```
assertion `left == right` failed
  left: Some(Err(()))
 right: Some(Ok(Group("[Desktop Entry]")))
```

**Comment by ivan770** [comment]
I'll close this issue, since the other similar regex works for me - `\[([ -Z\\^-~])+\]`

**Comment by jeertmans** [comment]
Hello @ivan770! I think this is still an interesting issue (maybe related to another open issue).

Did you check if the pattern match if you use it directly, i.e., not as a subpattern?

**Comment by jeertmans** [comment]
Ooohh I think the issue comes from the `?` lookahead, which is not supported by Logos iirc.

**Comment by jeertmans** [comment]
But `r#"\[[ -~]+\]"#` does not match `[Desktop Entry]`, because it does not match any letter?

**Comment by ivan770** [comment]
> But `r#"\[[ -~]+\]"#` does not match `[Desktop Entry]`, because it does not match any letter?

It's the same regex that I used with regex crate, and it works just fine there. It should match every printable ASCII character.

**Comment by jeertmans** [comment]
@ivan770 you are right, i didn't notice it was actually a valid range :'-) sorry for the confusion haha

The issue, I think, is that `]` is contained in ` -~`, so `logos` just tries to greedily match all characters, but never finds the ending bracket you are looking for.
