### ISSUE TITLE
Strange behavior, error when all input should be skipped

### ISSUE THREAD

**Issue by trueblablak** [maciejhirsz/logos#362]
Assert in following code fails:
```rust
use logos::Logos;

fn main() {
    let mut lexer = Token::lexer("\n\n use::blablabla");
    assert!(lexer.next().is_none());
}

#[derive(Debug, Logos)]
#[logos(skip r"[.\n ]")]
enum Token {
    #[regex(r"\$\d+")]
    X,
}
```

**Comment by jeertmans** [comment]
Hello, I think you expect `.` to match anything, but enclosing it inside square brackets, `[` and `]`, make it such that it should match a `.` character, see:

![image](https://github.com/maciejhirsz/logos/assets/27275099/0427ea58-af16-414b-9345-7504dc223a45)

from https://regex101.com/r/78s7TZ/1.

**Comment by trueblablak** [comment]
You're right, thanks!
