### ISSUE TITLE
[QUESTION] should I use logos for small strings?

### ISSUE THREAD

**Issue by test3211234** [maciejhirsz/logos#401]
Sorry, there's no discussions and I wanted to ask. For VSCode when clause contexts (search it up)-like strings (basically boolean expressions) which most of which are going to be this big: "!variable_1 && variable_2" with some being double that size in tokens, is Logos the best thing to use? You can close the issue after answering. I'm going to use a recursive AST to parse them.

And should I use nom for this?

**Comment by jeertmans** [comment]
Hello! Well I all depends on the size of your string and the size of what you are looking for. I think Logos is best suited when matching multiple more or less complex patterns, multiple times. It should be pretty fast, even of small strings, but some other libraries provides optimized searches if you only search for one string (and not regex).
