### ISSUE TITLE
[QUESTION] Why are tokens interspersed with `Err(())`s, even though the tokens themselves are correct?

### ISSUE THREAD

**Issue by test3211234** [maciejhirsz/logos#402]
It's weird. The errors have no effect because all the non token errors are in the right order and are correct, but it messes up my `while let Some(Ok(...))` loop.

![image](https://github.com/user-attachments/assets/a2ea4d46-b3be-42bb-97c0-03acd8406e65)

The test string:

`"inChatInput && voiceChatInProgress && scopedVoiceChatInProgress == editor || inChatInput && voiceChatInProgress && scopedVoiceChatInProgress == inline || inChatInput && voiceChatInProgress && scopedVoiceChatInProgress == quick || inChatInput && voiceChatInProgress && scopedVoiceChatInProgress == terminal || inChatInput && voiceChatInProgress && scopedVoiceChatInProgress == view || inlineChatFocused && voiceChatInProgress && scopedVoiceChatInProgress == editor || inlineChatFocused && voiceChatInProgress && scopedVoiceChatInProgress == inline || inlineChatFocused && voiceChatInProgress && scopedVoiceChatInProgress == quick || inlineChatFocused && voiceChatInProgress && scopedVoiceChatInProgress == terminal || inlineChatFocused && voiceChatInProgress && scopedVoiceChatInProgress == view"`

The `Token` enum:

```rust
#[derive(Logos, Debug, PartialEq, Eq)]
#[logos(skip r"[ ]+")]
pub enum Token<'src> {
    #[regex(r#"[a-zA-Z0-9_<>\-\./\\:\*\?\+\[\]\^,#@;"%\$\p{L}-]+"#)]
    Lexeme(&'src str),
    #[token("&&")]
    And,
    #[token("||")]
    Or,
    #[token("==")]
    Equal,
    #[token("!=")]
    NotEqual,
    #[token("!")]
    Not,
    #[token("(")]
    LParen,
    #[token(")")]
    RParen,
}
```

Thanks!

**Comment by jeertmans** [comment]
Hello! Thanks for asking this question. The `Err` variant occurs anytime Logos encounters a character (or byte) that isn't matched by any of the token variants.

Depending on your application, you could just ignore those by rewriting your code as follows:

```rust
while let Some(res) = lexer.next() {
    if let Ok(token) = res {
        /* your logic */
    }
}
```

However, I guess the errors should not occur here, as they seem to occur at whitespace, which should be skipped... And we can see the first white spaces are properly skipped.

Before I dig deeper into your issue, could you try to simplify your test string (reduce its length) and also your token definition to the simplest possible?

**Comment by test3211234** [comment]
I came back today and ran the exact same code and now there aren't errors. Huh? So I can't test what you said. Genuinely absolutely 0 idea as to why it suddenly works. I didn't change anything.

![image](https://github.com/user-attachments/assets/9cddcad8-50cb-4cdf-9114-5de0a63771c5)

By the way, I never had this problem on shorter strings, even though they had more complex tokens.

I have two other unrelated questions:
- Does `logos` support the regex syntax `\p{L}` to match all unicode letters? (I used it above.)
- What is the best way to match and get the content between double quotes like `"hello hi"`?

**Comment by jeertmans** [comment]
Maybe your string was malformed (you probably had invisible tabs `\t` or else).


> * Does `logos` support the regex syntax `\p{L}` to match all unicode letters? (I used it above.)
It should, since [`v0.14`](https://github.com/maciejhirsz/logos/releases/tag/v0.14), as we bumped `regex-syntax`.
> * What is the best way to match and get the content between double quotes like `"hello hi"`?
It depends, especially if your string can contain escaped quotes or not. If it can contain escaped quotes, then it is usually easier to have one token match `"`, and perform some post-processing logic to capture everything between two quotes.

**Comment by jeertmans** [comment]
Closing as your issue / question is now resolved :-)

**Comment by test3211234** [comment]
Could you elaborate on how to do the quote thing? This is how VSCode does it in their lexer. I don't need escaped quotes.

```js
// captures the lexeme without the leading and trailing '
	private _quotedString() {
		while (this._peek() !== CharCode.SingleQuote && !this._isAtEnd()) { // TODO@ulugbekna: add support for escaping ' ?
			this._advance();
		}

		if (this._isAtEnd()) {
			this._error(hintDidYouForgetToOpenOrCloseQuote);
			return;
		}

		// consume the closing '
		this._advance();

		this._tokens.push({ type: TokenType.QuotedStr, lexeme: this._input.substring(this._start + 1, this._current - 1), offset: this._start + 1 });
	}
```

**Comment by jeertmans** [comment]
In the above code, they handle a possibly missing end quote. This would require a custom lexing rule, and checks, etc. I have written a [JSON parser example](https://logos.maciej.codes/examples/json.html) that will check that every opening array / object has a matching end.

If you assume that all your string as terminated with a proper quote, then this regex might be sufficient: `"\"[^"]+\"`.

**Comment by test3211234** [comment]
I'm also wondering what the most idiomatic way to do this is.

In an expression, a `Lexeme` normally is considered a variable, and is parsed for a boolean value. However, if it's on the right side of an `==` or `!=`, then you know it's being compared to a variable, and that's only for strings, so it must be a string. What is the best way to differentiate between variables and literal strings?

Example:

`"bool_var && string_var == something"`

Here, `bool_var` and `string_var` should be treated as variables, but `something` should be treated as just a literal.


Here's my shunting yard algorithm implementation (converts boolean expression to reverse polish notation for fast evaluation later):

```rust

fn shunting_yard<'src>(
    lexer: &mut Lexer<'src, Token<'src>>,
) -> Result<Vec<Token<'src>>, ParseError> {
    let mut output = Vec::new();
    let mut operators: Vec<Token> = Vec::new();
    
    'outer: while let Some(res) = lexer.next() {
        if let Ok(token) = res {
            match token {
                Token::Lexeme(_) => {
                    output.push(token);
                }
                Token::And | Token::Or | Token::Not | Token::Equal | Token::NotEqual => {
                    while operators.last().map_or(false, |other_operator| {
                        other_operator.precedence() >= token.precedence()
                    }) {
                        output.push(operators.pop().unwrap());
                    }
    
                    operators.push(token);
                }
                Token::LParen => {
                    operators.push(token);
                }
                Token::RParen => {
                    while let Some(operator) = operators.pop() {
                        if operator == Token::LParen {
                            continue 'outer;
                        }
    
                        output.push(operator);
                    }
    
                    return Err(ParseError::MismatchedParen);
                }
            }
        }
    }

    while let Some(operator) = operators.pop() {
        if operator == Token::LParen {
            return Err(ParseError::MismatchedParen);
        }

        output.push(operator);
    }

    Ok(output)
}
```

I can't figure out a way to differentiate. When I parse the reverse polish notation, I have to be able to extract the token value, whether it's variable value, OR just the literal itself if it's a literal on the right of `==` or `!=` immediately. When they're all `Lexeme`s I can't do that. I don't want to force people to put quotes around literals and that's causing some problems. 

I was thinking you could put a new regex that's something like `(==|!=)[ ]+[a-zA-Z0-9_<>\-\./\\:\*\?\+\[\]\^,#@;"%\$\p{L}-]+`, but that just seems wrong and hacky. I was wondering if you know the most idiomatic/efficient way, whether at lex, parse or evaluate level, of how to do this. If you have any questions let me know. Sorry for the essay.

**Comment by test3211234** [comment]
Here's a solution I made. Do you know if there's a better way? That PR that lets you return tokens of another type helped me out here, but I had no I could do that until I saw it on the 0.14 changelog. The regex I provided above along with a split_whitespace could be better.

```rust
#[derive(Logos, Debug, PartialEq, Eq)]
#[logos(skip r"[ ]+", extras = bool)]
pub enum Token<'src> {
    #[regex(r#"[a-zA-Z0-9_<>\-\./\\:\*\?\+\[\]\^,#@;"%\$\p{L}-]+"#, variable_or_string)]
    Unknown,
    Variable(&'src str),
    String(&'src str),
    #[token("&&")]
    And,
    #[token("||")]
    Or,
    #[token("==", expect_string)]
    Equal,
    #[token("!=", expect_string)]
    NotEqual,
    #[token("!")]
    Not,
    #[token("(")]
    LParen,
    #[token(")")]
    RParen,
}


fn variable_or_string<'src>(lex: &mut Lexer<'src, Token<'src>>) -> Token<'src> {
    let slice = lex.slice();
    
    // Last token was ==
    if lex.extras {
        lex.extras = false;
        Token::String(slice)
    } else {
        Token::Variable(slice)
    }
}

fn expect_string<'src>(lex: &mut Lexer<'src, Token<'src>>) {
    lex.extras = true;
}
```

**Comment by jeertmans** [comment]
Thanks for sharing your code @test3211234! To me, it looks like a very good solution to your problem!
