### ISSUE TITLE
I set the priority but it doesn't seem to work

### ISSUE THREAD

**Issue by yIllusionSky** [maciejhirsz/logos#412]
As the title says, the code I use will always only match whitespace, not tab.

logos
```rust
#[token("    ", priority = 20)]
    #[token("\t")]
    Tab,
    #[regex(r"[ \r\f]+", logos::skip)]
    Whitespace,
```

test
```rust
let lex = r#"
                    1
        "#;
```

output
```text
Line
Whitespace
Number(1)
Line
Whitespace
```

**Comment by jeertmans** [comment]
Hello, this is not a bug, but an intended behavior. The priority is only used to choose between two tokens that match the same string. But if a token matches a longer string, than it is chosen (longer beats shorter). Maybe you should allow your tab token to match multiples tabs. That should solve your issue.

**Comment by yIllusionSky** [comment]
> Hello, this is not a bug, but an intended behavior. The priority is only used to choose between two tokens that match the same string. But if a token matches a longer string, than it is chosen (longer beats shorter). Maybe you should allow your tab token to match multiples tabs. That should solve your issue.

Thank you, I changed the writing method and the problem has been solved.

**Comment by jeertmans** [comment]
Glad it helped! Can you post your solution here please? So the next people will know how :)

**Comment by yIllusionSky** [comment]
> Glad it helped! Can you post your solution here please? So the next people will know how :)

It may not be the best solution, I made space match a single character
```rust
    #[token("\t")]
    Tab,
    #[token(" ", logos::skip)]
    Whitespace,
```

**Comment by jeertmans** [comment]
Thanks!
