### ISSUE TITLE
Using constants in #[regex()] macros

### ISSUE THREAD

**Issue by ccleve** [maciejhirsz/logos#417]
I have multiple lexers that use common, and lengthy, regexes. It would be nice to put each regex in a const and reference it in multiple times.

In general, Rust doesn't allow constants in macros because macros get evaluated first. But I though that a nested macro might work:
```

#[macro_export]
macro_rules! myregex {
    () => {
        "complicated_thing_here"
    };
}
...
enum MyLexer {

    #[regex(myregex!())]
    MyTokenType,

}

```
but I get:

```
error: expected literal
   |
41 |     #[regex(myregex!())]
   |             ^^^^^^^

```

Is it possible to define a regex string in one place and use it in multiple places?

**Comment by jeertmans** [comment]
Hello! As far as I know, this is not possible, see https://github.com/rust-lang/rust/issues/52393.

The short explanation is that the procedural macro `#[regex(<input>)]` needs to be able to read the content of `<intput>` as compilation time, which is not possible at the moment.

If you want to reuse some regex, you can still use subpatterns, see https://github.com/maciejhirsz/logos/issues/162.

Now, I just noticed that this should be documented somewhere in the book ^^', so I'll open an issue for that.

**Comment by jeertmans** [comment]
Closing this as this is a limitation of Rust, not Logos.
