### ISSUE TITLE
Latest patch bumped MSRV for logos-derive

### ISSUE THREAD

**Issue by elpiel** [maciejhirsz/logos#449]
Given that we used `protox` crate which has set logos to 0.14,since the latest update it now requires MSRV of 1.74.

What is your policy for MSRV bumping?
I see that the latest MSRV in the CHANGELOG was mentioned but not the latest one (for 0.14.3)

**Comment by jeertmans** [comment]
Indeed, we bumped the MSRV without documenting it, as we don't have any specific policy for this. I usually don't mind bumping MSRV if that enables new features, but we could at least document that.

**Comment by elpiel** [comment]
Yes, well protox defines MSRV which is what we use but logos broke that MSRV for protox, so now protox also doesn't have proper MSRV.
I don't mind when crates break builds because of msrv especially if the are only dev-deps, however, it's less than idea to set a third party crates versions to circumvent this though.

**Comment by jeertmans** [comment]
> Yes, well protox defines MSRV which is what we use but logos broke that MSRV for protox, so now protox also doesn't have proper MSRV.

You mean because of us, or because you never had a proper MSRV?

> I don't mind when crates break builds because of msrv especially if the are only dev-deps, however, it's less than idea to set a third party crates versions to circumvent this though.

I am not sure to understand the second part of your sentence. To me, it makes sense that bumping dependencies might require bumping your project's MSRV, no?

**Comment by maciejhirsz** [comment]
MSRV bump is technically a breaking change, so it should probably warrant a 0.15 release I reckon.

**Comment by elpiel** [comment]
> You mean because of us, or because you never had a proper MSRV?
 
I'm saying that we don't use logos directly but it broke our build even though protox has strict Msrv defined.

> I am not sure to understand the second part of your sentence. To me, it makes sense that bumping dependencies might require bumping your project's MSRV, no?

Not with path versions.


@maciejhirsz yes, I suppose a bump in the minor version would solve the issues for the  future.

**Comment by jeertmans** [comment]
> MSRV bump is technically a breaking change, so it should probably warrant a 0.15 release I reckon.

I agree that it can be considered a breaking change (e.g., dropping support for a Python version in is usually considered a breaking changes), but Rust is also very different as it releases new versions more frequently and update are very easy: all to say that it might be better to define a clear versioning policy.

> I'm saying that we don't use logos directly but it broke our build even though protox has strict Msrv defined.

Yeah, I forgot that Rust crates usually specify dependency versions as `x.y` and not `x.y.z`, meaning that the `z` (patch) part can be freely updated.

> Not with path versions.

It's true, this is just that I am more used to the standard semantic versioning, where bumping `x` means breaking changes`, bumping `y` means new features and `z` means fixes (i.e., patches). As we haven't reached `1.0.0` yet, I wasn't sure of what direction to take regarding versioning.

I will yank `0.14.3` and release it under `0.15`, so hopefully this will too many projects breaking.
