### ISSUE TITLE
Unicode properties increase compile time significantly

### ISSUE THREAD

**Issue by lylythechosenone** [maciejhirsz/logos#457]
The following code takes up to 10 seconds to compile on my machine:
```rust
#[derive(Logos)]
enum Token<'a> {
    #[regex(r"\p{XID_Start}\p{XID_Continue}+")]
    Ident(&'a str),
}
```
Additionally, whatever result is being computed is not cached, so builds take 10 seconds every single time. Replacing the properties with similar character sets, such as in `[a-zA-Z_][a-zA-Z0-9_]+`, fixes the problem (but, of course, does not do the same thing). Is this unavoidable? It makes it very hard to use logos in any IDE.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

To improve compilation speed for Unicode property patterns, we'll implement caching for regex patterns in the `logos-codegen` crate. This involves modifying the `Parser` struct to include a cache for compiled regex patterns, and updating the `parse_literal` method to use this cache.

You can review changes in this commit: https://github.com/jacks-sam1010/maciejhirsz-logos-457/commit/172ff9d12cdb326fe4f1378ca6df5f9dce2904aa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lylythechosenone** [comment]
...I don't understand, are you a human or a robot?

Regardless, this does not solve the problem as far as I can tell. It seems to just create a cache for each run, which is not helpful in this situation.

**Comment by jeertmans** [comment]
Hi @lylythechosenone! I think you underestimate the complexity hidden behind those Unicode properties: `\p{XID_Start}` covers way more than just `[a-zA-Z_][a-zA-Z0-9_]+`.

Take a look at the high-level intermediate representation of your regex: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c0a7ab84df1306526bb399b77fcbe2a8.

This is exactly this that we use to build a look-up-table, so it makes sense that it takes some time to generate, given the number of Unicode ranges we must cover.

> ...I don't understand, are you a human or a robot?

Not sure to understand this? Probably a bot that commented and deleted the message shortly after?

> Regardless, this does not solve the problem as far as I can tell. It seems to just create a cache for each run, which is not helpful in this situation.

This is related to how procedural macros work, we cannot really create a caching system or else. If you edit the file when `#[derive(Logos)]`, is will probably re-run the whole proc. macro again.

If your enum declaration never (or rarely) changes, you can use [`logos-cli`](https://crates.io/crates/logos-cli) tool to expand the macro once, and avoid re-generating the look-up table ever. For more details, checkout [Logos' internals](https://logos.maciej.codes/contributing/internals.html).

**Comment by lylythechosenone** [comment]
This is about what I was expecting. Thanks for the note about logos-cli, that looks like what I want.

And yes, that comment was in response to some AI attempting to "fix" the problem. Seems like it deleted itself or someone else deleted it.

**Comment by jeertmans** [comment]
Thanks for your reply! I will close this as there is nothing more we can really do about this, but feel free to re-open this issue if you think this is needed.
