### ISSUE TITLE
Fork regex issue

### ISSUE THREAD

**Issue by mikolajpp** [maciejhirsz/logos#59]
I am not entirely sure, so lets first settle it here if it is a bug or not. 
This works
```
#[regex="~s[0-9]+(\\.\\.[0-9a-f\\.]+)"]
#[regex="~s[0-9]+"]
LiteralRelDate
```
But collapsing the above regex into single one
```
#regex=["~[0-9]+(\\.\\.[0-9a-f\\.]+)?"]
```
Gives unexpected error on things that would otherwise match into LiteralRelDate in the former case.

**Comment by maciejhirsz** [comment]
Definitely a bug, can you provide tests / examples for breakage?

**Comment by mikolajpp** [comment]
Will send a PR soon; One question though, how do you work around 
```
--> tests/tests/properties.rs:2:5
  |
1 | use logos::Logos;
  |     ------------ previous import of the macro `Logos` here
2 | use logos_derive::Logos;
  |     ^^^^^^^^^^^^^^^^^^^ `Logos` reimported here
  |
  = note: `Logos` must be defined only once in the macro namespace of this module
help: you can use `as` to change the binding name of the import
  |
2 | use logos_derive::Logos as OtherLogos;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

or do you not see it? I am working from nigthly, and for every PR I have to comment it out 
the `use logos_derive` for testing, and then turn it back on.
