### ISSUE TITLE
Regex but Fast?

### ISSUE THREAD

**Issue by SafelySwift** [maciejhirsz/logos#69]
It seems like this lever uses regex, and then states that it is fast?
I have never worked with rust, as I am a pure Swift/C dev at this point, and was wondering if anyone can explain how this helps speed up over FSMs

**Comment by maciejhirsz** [comment]
All regex patterns are parsed and combined into a single tree, that is then used to generate Rust code for the lexer. All of that is done at compile time via the derive macro, so there is no runtime overhead, it's as if you wrote a [lexer like this](https://github.com/ratel-rust/ratel-core/blob/90355bb61620b6efd2da3697d503986b5ca51e5a/ratel/src/lexer/mod.rs) by hand, the whole code can be derived from simple token definitions.

**Comment by SafelySwift** [comment]
Gotta parse that 10 Gb file
