### ISSUE TITLE
"`Logos` reimported here"

### ISSUE THREAD

**Issue by cloudcalvin** [maciejhirsz/logos#77]
Hi there!

I am trying out your library but am having trouble with compiler errors:
```
 |
1 | use logos::Logos;
  |     ------------ previous import of the macro `Logos` here
2 | use logos_derive::Logos;
  |     ^^^^^^^^^^^^^^^^^^^ `Logos` reimported here
```
I am trying to to the Inner/Outer lexer switch as in the test example code.
If I DON'T specify `use logos_derive::Logos;` then the compiler says it cannot find `advance_as`,
and if I ONLY specify `use logos_derive::Logos;` then compiler complains about not finding `Outer::lexer(..`.

Kind regards
Calvin

**Comment by maciejhirsz** [comment]
The `logos` crate already re-exports the derive macro, so `use logos::Logos` imports both the trait and the macro. If you want to explicitly `use logos_derive::Logos` you'll need disable default features for the `logos` crate.

The `advance_as` method is pretty new, are you sure you are on the latest `0.10.0-rc2`?

**Comment by maciejhirsz** [comment]
If this still happens with default-features disabled in `logos`, [the solution is](https://github.com/maciejhirsz/logos/blob/3c9537d66dd478a910c86d414b46d5f377ef0484/tests/tests/lexer_modes.rs#L1-L2):

```rust
use logos::Logos as _; // Import trait anonymously, so trait methods are available
use logos_derive::Logos; // Import the derive macro, so #[derive(Logos)] works
```
