### ISSUE TITLE
Eats up all my RAM during building then dies.

### ISSUE THREAD

**Issue by Amanita-muscaria** [maciejhirsz/logos#78]
So I'm realizing that what I actually need is a parser/lexer. However, I don't know if that relates to chewing up all the memory or not so I figured I'd submit this anyway just in case it helps solve a problem.

This is the lexer I'm working with

```Rust
#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[end]
    End,
    #[error]
    Error,

    // #[regex = r"(?s)/\*.*\*/"]
    // BlockCommentStart,
    //
    // #[regex = r"//.*\n?"]
    // LineComment,

    #[regex = r"/\s*\{"]
    RootNode,

    #[regex = r"\s*([[:digit:][:alpha:]_]*:)?\s*[[:digit:][:alpha:],._+@-]*\s*\{"]
    Node,

    #[regex = r"\s*};"]
    NodeEnd,

    #[regex = r#"(?m)\s*[#[:digit:][:alpha:],._+-]*\s*=\s*(<|"|\[)[[:alpha:][:digit:],]*(>|"|\]);"#]
    Property,

    #[regex = r"\s/[[:alpha:]-]*/\s[[:alpha:][:digit:]_&@-]*;\n?"]
    Directive,

    #[regex = r#"\s*#include (<|")[[:alpha:][:digit:]_-]*\.(h|(dtsi))(>|")"#]
    Include,

    // #[regex = r"\s*[[:alpha:][:digit:],#]*\n"]
    // NonStdProperty,
}
```

The problem is that, in addition to taking forever to finish, it will use up all 16GB of RAM on my machine and then die when it tries to grab another ~41MB at some point. 

If this is doing more than what Logos is supposed to, go ahead and close this out.

**Comment by maciejhirsz** [comment]
Going to aggregate this under #70.
