### ISSUE TITLE
`logos_derive` melts the CPU for XID, then gets a SIGKILL

### ISSUE THREAD

**Issue by Evrey** [maciejhirsz/logos#79]
Given this token rule:
```Rust
    #[regex = r"\p{XID_Start}\p{XID_Continue}*"]
    LiteralIdentifier,
```
… `logos` will spin up a single CPU core to 100%, then receive a `SIGKILL` if the core overheats. Otherwise, when my laptop manages to keep the core from overheating, compilation seems to take a billion years. Well, at least 5min. I `Ctrl`+`C`d out of impatience. RAM usage is pretty low, though.

So things that might help:
- Find opportunities to parallelise the work.
- Figure out when work takes too long and maybe `sleep` for a little or be `nice`.
- Whatever else helps getting this beast to work.

Until then I'll have to use ASCII identifiers. ),:

**Edit:** Using v0.9.7 from https://crates.io/

**Edit 2:** Compilation never seems to finish. With successful cooling, the core still overheats. And `logos` starts using a lot of RAM, so might also be related to #78 .

**Comment by Evrey** [comment]
#78 and this one can be merged. When trying to compile something with quite the state explosion, the CPUs spin up to 100%, and memory usage grows exponentially. When compiling with `-j 1`, `logos` builds slowly enough for me to not overheat the CPU, then continues to consume enough RAM so that everything hangs thanks to excessive thrashing.

**Comment by maciejhirsz** [comment]
Aggregate into #70.
