### ISSUE TITLE
Incorrect regex with parentheses

### ISSUE THREAD

**Issue by wirelyre** [maciejhirsz/logos#81]
This lexer:

```rust
#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[end] End,
    #[error] Error,

    #[regex = "a(a)+"] Aaa,
}
```

incorrectly matches a single `a`. Changing the regex to `aa+` makes it work correctly.

**Comment by maciejhirsz** [comment]
This should be fixed with 0.10.0-rc3, please re-open if it happens again.
