### ISSUE TITLE
How do I peek?

### ISSUE THREAD

**Issue by sanboxrunner** [maciejhirsz/logos#82]
Hello! Sorry to use this as an issue, but how do I use the Lexer to peek? I saw on reddit that creator of this project said that this was better since you didn't have to wrap it in a Peekable, but I don't see how to peek at all!

By peek, I mean the classic:
```
if my_lexer.peek() == TokenType::whatever {
    // consume
}
```

Thank you!

**Comment by maciejhirsz** [comment]
Not sure if you figured it out, but in case and for anyone else looking in the future, `lexer.token` is effectively a peek.

**Comment by jkbbwr** [comment]
For anyone that comes to this in the future.

```rust
let lexer = Token::lexer(source);
let mut peekable_lexer: Peekable<Lexer<Token>> = lexer.peekable();
let next = peek_iterator.peek();
println!("{:?}", next);
```
