### ISSUE TITLE
We need 'lexer.peek()'

### ISSUE THREAD

**Issue by Aloure** [maciejhirsz/logos#84]
So I'm writing a programming language using this library and using a hand-written LL parser. The problem is that I need to peek the next token enum but I can't seem to find a way.

I tried to:
* Copy or clone the lexer but it says no Copy/Clone implemented.
* Change the token_start and token_end but they are private so I can't really touch them.

I believe everyone needs that. If you want, I can make a PR or I can wait if you want to implement it yourself. But for now...

...I'm asking the owner, how the hell do we peek using this wonderful library?

**Comment by Aloure** [comment]
Sorry, I figured out. I was using in cargo.toml
``` toml
logos = "*"
```

Changed that to:
``` toml
logos = { git = "https://github.com/maciejhirsz/logos/" }
```

Now I can clone lexer and it doesn't give error. Closing the issue...
> (PS: Thanks for this beautiful library btw)

**Comment by maciejhirsz** [comment]
FYI, you can just do `logos = "0.10.0-rc2"` to get the latest version (being a non-stable version, cargo won't fetch it with `"*"`).
