### ISSUE TITLE
The macro #[regex=r"[\w]+"] make rustc get stuck and crash.

### ISSUE THREAD

**Issue by pzzp** [maciejhirsz/logos#87]
![image](https://user-images.githubusercontent.com/21138299/66552091-515c0280-eb7b-11e9-8dcf-bd1de10a7790.png)

Look at the picture. 
If I didn't cancel it, the rustc will be stuck for a long time and then tell a error.  Sometimes it even make my system crash.

**Comment by maciejhirsz** [comment]
This should be fixed in 0.10.0-rc3.
