### ISSUE TITLE
Comparison to lex

### ISSUE THREAD

**Issue by ids1024** [maciejhirsz/logos#90]
Essentially the "standard" technique for efficient lexing is to combine regular expressions into a single optimal DFA. This is used by the standard Unix tool lex/flex and described in the classic [Dragon Book](https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools).

I was expecting a fast lexing crate to do the same. But it seems to not do that; though the implementation is clearly not just a naive approach to lexing either.

It would be convenient if the README included a comparison section, in terms of overall performance and other aspects. I might run some tests comparing the two myself, but I think I'll just post an issue here first anyway.

**Comment by maciejhirsz** [comment]
@ids1024 Logos is effectively a state machine. The upcoming version (#94) is built from a graph of nodes (states) that can do arbitrary jumps to other nodes (states) until a token is lexed. The currently released version isn't really different in principle, except for the fact that it constructs a tree of states, which bloats things up considerably.

**Comment by maciejhirsz** [comment]
The readme is much more explicit now.
