### ISSUE TITLE
Detect EOF in regular expressions

### ISSUE THREAD

**Issue by ebkalderon** [maciejhirsz/logos#91]
It would be nice if the `\W` anchor was supported in `#[regex]` strings such that certain regular expressions could succeed if EOF is encountered early. For example:

```rust
#[derive(Logos)]
enum Token {
    #[end]
    End,
    #[error]
    Error,
    #[regex = r"/\*([^*]|\*+[^*/]|[^\W])*(\*+/|\W)"]
    BlockComment,
}
```

The regex shown above would be able to match both `/* hello */` and also `/* hello`, where the second one is immediately followed by an `#[end]`. This would allow for the lexer to process the token successfully even if the input terminates early before the `*/` could be received, and we could check whether the comment is properly terminated by calling `lexer.slice().ends_with("*/")` at a later stage.

See [`TokenKind::BlockComment { terminated: bool }`](https://github.com/rust-lang/rust/blob/master/src/librustc_lexer/src/lib.rs#L47) in `rustc_lexer` for an example of this common lexing pattern.

**Comment by maciejhirsz** [comment]
Might still add this to regex itself, but you will be able to handle this with callbacks next release, reference: #103.

**Comment by jeertmans** [comment]
Closing this a too old, feel free to re-open if needed.
