### ISSUE TITLE
Incorrect tokenizing

### ISSUE THREAD

**Issue by Kixiron** [maciejhirsz/logos#95]
Found a bug where the string `bredcp` is tokenized as
```rust
Token { ty: Ident, source: "br", range: 0..2 }
Token { ty: Ident, source: "bredcp", range: 0..6 }
```
Instead of 
```rust
Token {
    ty: TokenType::Ident,
    source: "bredcp",
    range: (0, 6)
}
```
The ident token is [here](https://github.com/Kixiron/crunch-lang/blob/dev/crates/crunch-parser/src/token.rs#L16-L17), and it's extra confusing because I don't have any tokens that are remotely close to `br`, plus the fact that it's being somehow *re*tokenized (As indicated by the ranges of the tokens makes this even stranger.
I also made a [test case](https://github.com/Kixiron/crunch-lang/blob/dev/crates/crunch-parser/src/token.rs#L443-L456) that exemplifies this error. I do have a small iterator adapter wrapped around logos, but this shouldn't have any effect as all it does is filter out unused tokens

**Comment by Kixiron** [comment]
It seems this also happens with the input `breuyue`, is there something inside my regexes that I'm missing?

**Comment by maciejhirsz** [comment]
If this is happening on 0.10 then this is likely same issue as #88. I'm doing a full rewrite of the derive macro right now (#94), which should solve these, amongst other things.

**Comment by maciejhirsz** [comment]
@Kixiron I've just released 0.10.0-rc3 on crates.io, could you update and check if the issue persists?

**Comment by Kixiron** [comment]
I switched versions and have been greeted with 48 of these:
```rust
error[E0308]: mismatched types
 --> crates\crunch-parser\src\token.rs:6:10
  |
6 | #[derive(Logos, Debug, PartialEq, Eq, Clone, Copy, Hash)]
  |          ^^^^^ expected fn item, found a different fn item
  |
  = note: expected fn item `for<'r> fn(&'r mut logos::lexer::Lexer<token::TokenType, _>) {<token::TokenType as logos::Logos>::lexicon::_handle_0_newline::<'_, _>}`
             found fn item `for<'r> fn(&'r mut logos::lexer::Lexer<token::TokenType, _>) {<token::TokenType as logos::Logos>::lexicon::_error::<'_, _>}`
```

**Comment by maciejhirsz** [comment]
Oh, I'm so sorry, I didn't bump the dependency in `logos` itself and I kept testing it with separate imports.

**Comment by Kixiron** [comment]
It fixed the problem this issue is about, but it caused a regression to one of my previously found bugs in logos
```rust
    #[test]
    fn keyword_led_ident() {
        let mut exposed_function = TokenStream::new("exposed_function", true).into_iter();

        assert_eq!(
            exposed_function.next(),
            Some(Token {
                ty: TokenType::Ident,
                source: "exposed_function",
                range: (0, 16)
            })
        );
        assert_eq!(exposed_function.next(), None);
    }
```
```
---- token::tests::keyword_led_ident stdout ----
thread 'token::tests::keyword_led_ident' panicked at 'assertion failed: `(left == right)`
  left: `Some(Token { ty: Exposed, source: "exposed", range: 0..7 })`,
 right: `Some(Token { ty: Ident, source: "exposed_function", range: 0..16 })`', crates\crunch-parser\src\token.rs:492:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by maciejhirsz** [comment]
A-ha, gotcha. I narrowed it down to the interaction of these 3:
```rust
    #[token = "else"]
    Else,
    #[regex = "[^ \t\n\r\"\'!@#$%\\^&*()-+=,.<>/?;:\\[\\]{}\\\\|`~]+"]
    Ident,
    #[token = "exposed"]
    Exposed,
```

What happens is, combining `else` with `exposed` produces a fork, and it seems the loop doesn't propagate correctly in all branches. That should be a pretty narrow problem to track.

I can run tests on `crunch` myself, are all the ones with `#[ignore]` Logos related?

**Comment by Kixiron** [comment]
Running tests is a little finicky, as I'm in the midst of a total rewrite, you have to cd into `crates/crunch-parser` before it'll work. As for ignored tests, as of now I don't have any, you may be on the wrong branch. My current development is on the `dev` branch, with logos residing [here](https://github.com/Kixiron/crunch-lang/blob/dev/crates/crunch-parser/src/token.rs). The test that's currently failing is [here](https://github.com/Kixiron/crunch-lang/blob/dev/crates/crunch-parser/src/token.rs#L483)

**Comment by Kixiron** [comment]
And thank you so much for the hard work, logos is a fantastic crate and your work is very much appreciated!

**Comment by maciejhirsz** [comment]
Well, I went to bed, but then I figured out how to solve this while I was trying to fall asleep :man_shrugging:.
