### ISSUE TITLE
Invariants held by diasllowing enum discriminants

### ISSUE THREAD

**Issue by ratmice** [maciejhirsz/logos#96]
This is more of a question, which I was wondering about,
If one tries to set a discriminant on a Token e.g.

```rust
enum Token { #[end] End = 0 }
```
Logos will produce:
> error: `Token::End` has a discriminant value set. This is not allowed for Tokens.

When converting token to a numerical type with as, the tokens appear to sequence 0, ...
But i haven't tracked down anything which ensure this yet.

Is logos by disallowing ensuring an invariant that the derived enum is 0 based and sequential?
If so, is this something that could be relied upon as part of its public API?

**Comment by maciejhirsz** [comment]
An `enum` with only unit variants, will have discriminants set by default, counting from `0` in order they are defined. You can see this is you do the following:

```
enum Foo {
    Bar,
    Baz = 0,
}
```
Produces error:
```
error[E0081]: discriminant value `0` already exists
 --> src/lib.rs:3:11
  |
2 |     Bar,
  |     --- first use of `0`
3 |     Baz = 0,
  |           ^ enum already has `0`
```

The rule to disallow discriminants is predetermined on the existence of the [`lookup!` macro](https://docs.rs/logos/0.9.7/logos/macro.lookup.html), it uses the `SIZE` associated const of the `Logos` trait to figure out a size of a lookup table that needs to be constructed, and allows you to index into it by casting the token enum as usize.

In principle we could relax this constraint, all that needs to be done to make sure that SIZE equals largest discriminant set (either explicit or implicit) + 1.

**Comment by ratmice** [comment]
I only really wanted to ensure the first was zero, 
```rust
enum Foo {
    Bar = 0,
    Baz,
}
```
perhaps an error check like the following?
```rust

        if Some(0) != variant.discriminant {
            panic!(
                "`{}::{}` has a non-zero discriminant value set. This is not allowed for Tokens.",
                name, variant.ident
            );
        }
```

**Comment by maciejhirsz** [comment]
Gonna constraint it to the number of variants, that's more relaxed than straight out disallowing setting the values while not having any unforeseen consequences. Will push to `rewrite` in a minute:

```
error: `Token::Error` discriminant value is too large. Value should be smaller than number of variants (20).
 --> tests/tests/advanced.rs:7:13
  |
7 |     Error = 1000,
  |             ^^^^
```

**Comment by maciejhirsz** [comment]
Pushed.

**Comment by maciejhirsz** [comment]
@ratmice I've been refactoring some code, found this check, and recalled talking about relaxing this further. If there isn't an open issue for this and you still need this, open one and I'll flag it for 0.11.1.

**Comment by ratmice** [comment]
@maciejhirsz I still need to do some refactoring before I can fully make use of the existing relaxation above in my program (for reasons not relevant to logos).  So at this point I'll leave that decision up to you?

**Comment by maciejhirsz** [comment]
I forgot to mention in in release notes, but I already did relax it just now in 0.11.1. If you have 3 variants, and you set discriminant `= 9` to one of them, `T::SIZE` will automatically bump to `10` without any errors.

So, you should be good to go :)
